-- ════════════════════════════════════════════════════════
-- TEAM MAP — seed đầy đủ mọi quy mô (sinh tự động bởi scripts/gen_team_map_seed.py, đừng sửa tay)
-- Chạy sau supabase_team_map.sql cho DB mới. Upsert theo id: chạy lại sẽ ghi đè nội dung đã sửa trong CMS.
-- DB đã có dữ liệu và chỉ cần thêm quy mô Agency: dùng supabase_team_map_agency_seed.sql.
-- ════════════════════════════════════════════════════════
begin;

-- 1. Phòng ban (chỉ nội dung; hình học nằm trong team-map/team-map.layout.js)
insert into tm_rooms (id, scale, code, name, intro, sort_order, i18n) values
  ('P1', 'small', 'Team 1', 'Product team', 'Đây là chỗ của bạn. Product Manager quyết định làm gì và theo thứ tự nào, bạn thiết kế, Intern học cùng bạn. Ở công ty nhỏ, designer thường kiêm luôn research và viết nội dung giao diện.', 0, '{"en": {"code": "Team 1", "name": "Product team", "intro": "This is your spot. The Product Manager decides what to build and in what order, you design, and the Intern learns alongside you. In a small company, designers often handle research and interface copy too."}}'::jsonb),
  ('P2', 'small', 'Team 2', 'Dev team', 'Tech Lead, Frontend, Backend, Mobile và QA biến thiết kế thành sản phẩm chạy được. Bạn sẽ sang đây để handoff, trả lời câu hỏi và review bản build.', 1, '{"en": {"code": "Team 2", "name": "Dev team", "intro": "The Tech Lead, Frontend, Backend, Mobile and QA turn designs into a working product. You come here to hand off, answer questions and review builds."}}'::jsonb),
  ('P3', 'small', 'Team 3', 'Business team', 'CEO, Marketing, Sales, Customer Support và Business Analyst. Nơi đặt mục tiêu kinh doanh và nghe tiếng nói khách hàng, nguồn insight quý cho thiết kế.', 2, '{"en": {"code": "Team 3", "name": "Business team", "intro": "The CEO, Marketing, Sales, Customer Support and the Business Analyst. This is where business goals are set and the customer''s voice is heard, a valuable source of insight for design."}}'::jsonb),
  ('P4', 'small', 'Họp', 'Phòng họp', 'Phòng dùng cho Sprint Planning, demo cuối sprint và các buổi họp cả công ty. TV để trình bày thiết kế.', 3, '{"en": {"code": "Meeting", "name": "Meeting room", "intro": "Used for Sprint Planning, end-of-sprint demos and company-wide meetings. The TV is for presenting designs."}}'::jsonb),
  ('P5', 'small', 'Chung', 'Pantry', 'Khu chung để nghỉ, gặp gỡ ngẫu nhiên và sinh hoạt guild. Nhiều ý tưởng hay bắt đầu từ một cuộc nói chuyện ở đây.', 4, '{"en": {"code": "Shared", "name": "Pantry", "intro": "A shared space for breaks, chance encounters and guild meetups. Many good ideas start with a chat here."}}'::jsonb),
  ('P6', 'small', 'Đóng', 'Phòng ban khác', null, 5, '{"en": {"code": "Closed", "name": "Other departments"}}'::jsonb),
  ('R01', 'large', 'R01', 'Leadership', 'CEO, CPO, CTO và các Head. Đặt chiến lược và OKR cho cả công ty. Head of Design là quản lý chuyên môn cao nhất của bạn.', 0, '{"en": {"code": "R01", "name": "Leadership", "intro": "The CEO, CPO, CTO and the Heads. They set strategy and OKRs for the whole company. The Head of Design is your most senior craft manager."}}'::jsonb),
  ('R07', 'large', 'R07', 'Data & Analytics', 'Data Analyst, BI Analyst, Data Scientist và Data Engineer. Ghé đây khi cần số liệu funnel hay kết quả A/B test.', 1, '{"en": {"code": "R07", "name": "Data & Analytics", "intro": "Data Analyst, BI Analyst, Data Scientist and Data Engineer. Drop by when you need funnel numbers or A/B test results."}}'::jsonb),
  ('R08', 'large', 'R08', 'Phòng họp', 'Sprint Planning và Sprint Review diễn ra ở đây. Stakeholder thường tới dự buổi demo.', 2, '{"en": {"code": "R08", "name": "Meeting room", "intro": "Sprint Planning and Sprint Review happen here. Stakeholders often come to the demo."}}'::jsonb),
  ('R02', 'large', 'R02', 'Tribe Growth', 'Các squad lo onboarding, kích hoạt và giới thiệu bạn bè. Designer ở đây làm việc nhiều với A/B test và số liệu tăng trưởng.', 3, '{"en": {"code": "R02", "name": "Tribe Growth", "intro": "The squads behind onboarding, activation and referrals. Designers here work a lot with A/B tests and growth metrics."}}'::jsonb),
  ('R03', 'large', 'R03', 'Core Experience', 'Squad của bạn: PM, designer, Tech Lead, dev và QA ngồi chung một bàn. Đây là nơi bạn làm việc hằng ngày.', 4, '{"en": {"code": "R03", "name": "Core Experience", "intro": "Your squad: the PM, designers, Tech Lead, developers and QA share one table. This is where you work every day."}}'::jsonb),
  ('R04', 'large', 'R04', 'Monetization', 'Squad lo thanh toán và gói dịch vụ. Designer ở đây làm việc sát với các ràng buộc về giá và pháp lý.', 5, '{"en": {"code": "R04", "name": "Monetization", "intro": "The squad behind payments and plans. Designers here work closely with pricing and legal constraints."}}'::jsonb),
  ('R05', 'large', 'R05', 'Platform', 'DevOps, Software Architect và team Design System. Hỏi team Design System trước khi vẽ một component mới.', 6, '{"en": {"code": "R05", "name": "Platform", "intro": "DevOps, the Software Architect and the Design System team. Ask the Design System team before drawing a new component."}}'::jsonb),
  ('R06', 'large', 'R06', 'Design Studio', 'Ngôi nhà chuyên môn của designer: Design Manager, UX Researcher, UX Writer, Motion Designer. Buổi Design Critique diễn ra hằng tuần ở đây.', 7, '{"en": {"code": "R06", "name": "Design Studio", "intro": "The craft home for designers: Design Manager, UX Researcher, UX Writer, Motion Designer. Design Critique happens here every week."}}'::jsonb),
  ('R09', 'large', 'R09', 'Delivery Hub', 'Scrum Master, Delivery Manager và Project Manager giữ nhịp sprint và hạn chót phát hành.', 8, '{"en": {"code": "R09", "name": "Delivery Hub", "intro": "The Scrum Master, Delivery Manager and Project Manager keep the sprint rhythm and the release deadlines."}}'::jsonb),
  ('R11', 'large', 'Chung', 'Pantry', 'Khu chung để nghỉ, gặp gỡ ngẫu nhiên và sinh hoạt guild. Người dùng được mời tới phỏng vấn cũng hay ngồi chờ ở đây.', 9, '{"en": {"code": "Shared", "name": "Pantry", "intro": "A shared space for breaks, chance encounters and guild meetups. Users invited for interviews often wait here too."}}'::jsonb),
  ('R10', 'large', 'R10', 'Hàng xóm · ngoài vách kính', 'Marketing, Customer Success, Sales và Business Analyst ngồi ngoài vách kính. Họ là những stakeholder bạn làm việc cùng thường xuyên.', 10, '{"en": {"code": "R10", "name": "Neighbours · behind the glass", "intro": "Marketing, Customer Success, Sales and the Business Analyst sit behind the glass wall. They are the stakeholders you work with most often."}}'::jsonb),
  ('A1', 'agency', 'Team 1', 'Design team', 'Ở agency bạn làm nhiều dự án cùng lúc, mỗi dự án một ngành khác nhau. Học nhanh và rộng, nhưng ít khi theo một sản phẩm đủ lâu để thấy kết quả. Người duyệt thiết kế của bạn là Design Director.', 0, '{"en": {"code": "Team 1", "name": "Design team", "intro": "At an agency you work on several projects at once, each in a different industry. You learn fast and wide, but rarely stay on one product long enough to see the results. Your designs are approved by the Design Director."}}'::jsonb),
  ('A2', 'agency', 'Team 2', 'Dev team', 'Một dev ở đây có thể chạy 2–3 dự án cùng lúc và thường không dự các buổi họp với khách. File thiết kế của bạn phải tự nói được mọi thứ.', 1, '{"en": {"code": "Team 2", "name": "Dev team", "intro": "A developer here may run 2–3 projects at once and usually skips client meetings. Your design files have to explain everything on their own."}}'::jsonb),
  ('A3', 'agency', 'Team 3', 'Account & Project', 'Mọi yêu cầu của khách hàng đi qua đây. Account Manager giữ quan hệ, Project Manager giữ phạm vi, tiến độ và ngân sách. Đừng tự hứa gì với khách khi chưa hỏi Project Manager.', 2, '{"en": {"code": "Team 3", "name": "Account & Project", "intro": "Every client request goes through here. The Account Manager owns the relationship, the Project Manager owns scope, schedule and budget. Never promise the client anything before checking with the Project Manager."}}'::jsonb),
  ('A4', 'agency', 'Họp', 'Phòng họp khách hàng', 'Nơi trình bày concept và nghe phản hồi của khách. Thiết kế tốt mà trình bày không rõ thì vẫn bị bác: ở agency, kỹ năng thuyết trình quan trọng ngang kỹ năng vẽ.', 3, '{"en": {"code": "Meeting", "name": "Client meeting room", "intro": "Where concepts are presented and client feedback is heard. A good design that is presented badly still gets rejected: at an agency, presenting matters as much as designing."}}'::jsonb),
  ('A5', 'agency', 'Chung', 'Pantry', 'Khu chung để nghỉ và gặp gỡ. Người dùng được mời tới dùng thử sản phẩm của khách cũng ngồi chờ ở đây.', 4, '{"en": {"code": "Shared", "name": "Pantry", "intro": "A shared space for breaks and meetups. Users invited to try the client''s product wait here too."}}'::jsonb),
  ('A6', 'agency', 'Team 4', 'Sales', 'Nơi mang dự án về cho công ty. Designer hay được nhờ dựng nhanh một bản demo để Sales đi thuyết phục khách ký hợp đồng.', 5, '{"en": {"code": "Team 4", "name": "Sales", "intro": "Where projects come into the company. Designers are often asked to put together a quick demo so Sales can convince clients to sign."}}'::jsonb)
on conflict (id) do update set scale = excluded.scale, code = excluded.code, name = excluded.name, intro = excluded.intro, sort_order = excluded.sort_order, i18n = excluded.i18n;

-- 2. Nhân vật (lượt 1: chưa gắn báo cáo cho ai)
insert into tm_characters (id, title, kind, "group", article_url, summary, doing, with_designer, props, appearance, tag, cta, is_active, i18n) values
  ('ceo', 'Chief Executive Officer', 'role', 'business', null, 'Người chịu trách nhiệm cao nhất về tầm nhìn và kết quả kinh doanh của công ty.', 'Đang xem lại OKR quý này với ban lãnh đạo.', 'Ít làm việc trực tiếp với designer, nhưng mục tiêu công ty do CEO đặt ra quyết định bạn thiết kế cho điều gì.', '["briefcase"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "The person ultimately responsible for the company''s vision and business results.", "doing": "Reviewing this quarter''s OKRs with the leadership team.", "with_designer": "Rarely works with designers directly, but the company goals the CEO sets decide what you design for."}}'::jsonb),
  ('cpo', 'Chief Product Officer', 'role', 'product', null, 'Chịu trách nhiệm chiến lược sản phẩm và quản lý đội ngũ Product Manager.', 'Đang chốt roadmap cho hai quý tới.', 'Duyệt các hướng sản phẩm lớn. Bạn sẽ trình bày với CPO ở các buổi review chiến lược.', '["flag"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Owns product strategy and manages the team of Product Managers.", "doing": "Finalising the roadmap for the next two quarters.", "with_designer": "Approves big product directions. You will present to the CPO at strategy reviews."}}'::jsonb),
  ('cto', 'Chief Technology Officer', 'role', 'engineering', null, 'Chịu trách nhiệm công nghệ, kiến trúc hệ thống và đội ngũ kỹ sư.', 'Đang rà soát chi phí hạ tầng tháng này.', 'Quyết định các giới hạn kỹ thuật, ảnh hưởng tới những gì designer có thể đề xuất.', '["laptop"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Owns technology, system architecture and the engineering team.", "doing": "Reviewing this month''s infrastructure costs.", "with_designer": "Sets the technical constraints, which shape what designers can propose."}}'::jsonb),
  ('head-of-design', 'Head of Design', 'role', 'design', null, 'Lãnh đạo toàn bộ chapter Design: tuyển dụng, chất lượng thiết kế và lộ trình phát triển của designer.', 'Đang xây khung năng lực cho các cấp designer.', 'Quản lý chuyên môn cao nhất của bạn (solid line). Bạn gặp ở các buổi all-hands của Design.', '["glasses", "pointer"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Leads the whole Design chapter: hiring, design quality and career paths for designers.", "doing": "Building a competency framework for every designer level.", "with_designer": "Your most senior craft manager (solid line). You meet at Design all-hands."}}'::jsonb),
  ('head-of-data', 'Head of Data', 'role', 'data', null, 'Lãnh đạo đội Data & Analytics và chuẩn hoá cách công ty đo lường.', 'Đang chuẩn hoá bộ chỉ số North Star.', 'Cung cấp số liệu để đánh giá một thiết kế có hiệu quả hay không.', '["chart"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Leads the Data & Analytics team and standardises how the company measures things.", "doing": "Standardising the North Star metrics.", "with_designer": "Provides the numbers that tell you whether a design actually works."}}'::jsonb),
  ('head-of-eng', 'Head of Engineering', 'role', 'engineering', null, 'Quản lý các Engineering Manager, QA Lead và chất lượng kỹ thuật chung.', 'Đang sắp xếp nhân sự cho squad mới.', 'Ít làm trực tiếp, nhưng quyết định tốc độ và cách các dev làm việc với bạn.', '["headset"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Manages the Engineering Managers, the QA Lead and overall engineering quality.", "doing": "Staffing a new squad.", "with_designer": "Rarely works with you directly, but decides how fast developers move and how they work with you."}}'::jsonb),
  ('product-manager', 'Product Manager', 'role', 'product', 'https://academy.telos.vn/product-manager-pm-la-gi-product-team/', 'Người chịu trách nhiệm về định hướng và kết quả sản phẩm: cần làm gì, tại sao, và theo thứ tự nào.', 'Đang viết user story cho luồng onboarding.', 'Đặt ưu tiên công việc cho bạn mỗi sprint (dotted line). Là người bạn trao đổi nhiều nhất mỗi ngày.', '["clipboard"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Owns the direction and outcomes of the product: what to build, why, and in what order.", "doing": "Writing user stories for the onboarding flow.", "with_designer": "Sets your priorities every sprint (dotted line). The person you talk to most every day."}}'::jsonb),
  ('product-owner', 'Product Owner', 'role', 'product', 'https://academy.telos.vn/product-owner-po-la-gi/', 'Vai trò Scrum quản lý product backlog và quyết định ưu tiên cho từng sprint.', 'Đang sắp xếp backlog cho sprint sau.', 'Làm rõ tiêu chí chấp nhận (acceptance criteria) cho từng thiết kế của bạn.', '["cards"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "The Scrum role that manages the product backlog and decides the priorities for each sprint.", "doing": "Ordering the backlog for next sprint.", "with_designer": "Clarifies the acceptance criteria for each of your designs."}}'::jsonb),
  ('growth-pm', 'Growth Product Manager', 'role', 'product', null, 'PM tập trung vào chỉ số tăng trưởng: kích hoạt, giữ chân, giới thiệu.', 'Đang đọc kết quả A/B test màn hình đăng ký.', 'Cùng bạn thiết kế thí nghiệm và đọc kết quả A/B test.', '["chart"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "A PM focused on growth metrics: activation, retention, referral.", "doing": "Reading the A/B test results for the sign-up screen.", "with_designer": "Designs experiments with you and reads the A/B test results together."}}'::jsonb),
  ('data-pm', 'Data Product Manager', 'role', 'product', null, 'PM cho các sản phẩm dữ liệu nội bộ như dashboard và hệ thống tracking.', 'Đang định nghĩa event tracking cho tính năng mới.', 'Giúp bạn gắn tracking đúng để đo hiệu quả thiết kế.', '["clipboard"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "A PM for internal data products such as dashboards and tracking systems.", "doing": "Defining event tracking for a new feature.", "with_designer": "Helps you set up the right tracking to measure how well a design performs."}}'::jsonb),
  ('ui-ux-designer', 'UI/UX Designer', 'player', 'design', 'https://academy.telos.vn/cong-viec-cua-ui-ux-designer/', 'Vai trò thiết kế giao diện và trải nghiệm người dùng: kết hợp tư duy UX và kỹ năng UI.', 'Đây là bạn. Bạn đang thiết kế luồng onboarding mới.', 'Ngồi trong squad, nhận ưu tiên từ PM, báo cáo chuyên môn cho Design Manager.', '["cap", "tablet"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Designs interfaces and user experiences, combining UX thinking with UI skills.", "doing": "This is you. You are designing a new onboarding flow.", "with_designer": "Sits in the squad, gets priorities from the PM, reports on craft to the Design Manager."}}'::jsonb),
  ('product-designer', 'Product Designer', 'role', 'design', 'https://academy.telos.vn/product-designer-la-gi-va-3-tu-duy/', 'Vai trò thiết kế toàn diện, từ research, UX đến UI, gắn liền với mục tiêu sản phẩm.', 'Đang vẽ user flow cho tính năng mời bạn bè.', 'Đồng nghiệp cùng chapter. Hai bạn hay gặp nhau ở buổi Design Critique.', '["tablet"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "An end-to-end design role, from research and UX to UI, tied closely to product goals.", "doing": "Drawing the user flow for the invite-a-friend feature.", "with_designer": "A colleague in the same chapter. You two often meet at Design Critique."}}'::jsonb),
  ('ui-designer', 'UI Designer', 'role', 'design', null, 'Tập trung vào giao diện: bố cục, màu sắc, chữ và component.', 'Đang hoàn thiện màn hình hồ sơ theo Design System.', 'Cùng chapter. Hay trao đổi với bạn về cách dùng component cho đúng.', '["palette"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Focuses on the interface: layout, colour, type and components.", "doing": "Polishing the profile screen to match the Design System.", "with_designer": "Same chapter. Often talks with you about using components the right way."}}'::jsonb),
  ('ux-designer', 'UX Designer', 'role', 'design', null, 'Tập trung vào trải nghiệm: luồng, cấu trúc thông tin và tương tác.', 'Đang vẽ lại luồng thanh toán còn 3 bước.', 'Cùng chapter. Hay cùng bạn review user flow trước khi lên UI.', '["pencil"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Focuses on the experience: flows, information architecture and interaction.", "doing": "Redrawing the checkout flow down to 3 steps.", "with_designer": "Same chapter. Often reviews user flows with you before moving to UI."}}'::jsonb),
  ('intern', 'Intern UI/UX', 'role', 'design', 'https://academy.telos.vn/intern-ui-ux-nhung-cam-nang-khi-di-thuc-tap/', 'Thực tập sinh UI/UX, học bằng cách làm cùng designer chính.', 'Đang tập vẽ wireframe theo hướng dẫn của bạn.', 'Bạn là người hướng dẫn trực tiếp. Intern hỏi bạn mọi thứ, từ file Figma đến cách họp.', '["backpack"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "A UI/UX intern who learns by working alongside a lead designer.", "doing": "Practising wireframes with your guidance.", "with_designer": "You are their direct mentor. The intern asks you everything, from Figma files to how meetings work."}}'::jsonb),
  ('ds-designer', 'Design System Designer', 'role', 'design', 'https://academy.telos.vn/design-system-designer-la-ai-product-design/', 'Xây và duy trì Design System: component library, token và guideline cho toàn sản phẩm.', 'Đang thêm biến thể mới cho component Button.', 'Hỏi họ trước khi vẽ một component mới. Có thể nó đã tồn tại.', '["palette"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Builds and maintains the Design System: the component library, tokens and guidelines for the whole product.", "doing": "Adding new variants to the Button component.", "with_designer": "Ask them before drawing a new component. It may already exist."}}'::jsonb),
  ('ux-design-engineer', 'UX Design Engineer', 'role', 'design', 'https://academy.telos.vn/ux-design-engineer-la-gi/', 'Kết hợp tư duy UX, thiết kế và code để tự triển khai trải nghiệm chất lượng cao.', 'Đang chuyển token màu từ Figma sang CSS.', 'Cầu nối giữa file Figma của bạn và code thật.', '["laptop"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Combines UX thinking, design and code to ship high-quality experiences themselves.", "doing": "Moving colour tokens from Figma into CSS.", "with_designer": "The bridge between your Figma file and real code."}}'::jsonb),
  ('design-manager', 'Design Manager', 'role', 'design', null, 'Quản lý trực tiếp các designer: review chất lượng, 1-on-1, phát triển nghề.', 'Đang chuẩn bị buổi Design Critique chiều nay.', 'Quản lý chuyên môn trực tiếp của bạn (solid line). Gặp 1-on-1 hai tuần một lần.', '["glasses", "pointer"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Directly manages designers: quality reviews, 1-on-1s, career growth.", "doing": "Preparing this afternoon''s Design Critique.", "with_designer": "Your direct craft manager (solid line). You have a 1-on-1 every two weeks."}}'::jsonb),
  ('ux-researcher', 'UX Researcher', 'role', 'design', null, 'Lên kế hoạch và thực hiện nghiên cứu người dùng.', 'Đang viết kịch bản cho buổi Usability Test.', 'Giúp bạn kiểm chứng thiết kế với người dùng thật trước khi build.', '["monocle", "clipboard"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Plans and runs user research.", "doing": "Writing the script for a Usability Test.", "with_designer": "Helps you validate designs with real users before anything gets built."}}'::jsonb),
  ('ux-writer', 'UX Writer & Content Designer', 'role', 'design', null, 'Viết chữ trong giao diện: nút, thông báo, hướng dẫn, trạng thái lỗi.', 'Đang viết lại thông báo lỗi đăng nhập.', 'Cùng bạn hoàn thiện câu chữ trên từng màn hình.', '["pencil"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Writes the words in the interface: buttons, messages, instructions, error states.", "doing": "Rewriting the login error messages.", "with_designer": "Polishes the copy on every screen with you."}}'::jsonb),
  ('motion-designer', 'Motion Designer', 'role', 'design', 'https://academy.telos.vn/motion-designer-la-ai-product-design/', 'Tạo chuyển động và animation trong sản phẩm, từ micro-interaction đến transition.', 'Đang làm animation chuyển cảnh cho onboarding.', 'Biến các tương tác bạn thiết kế thành chuyển động mượt.', '["play"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Creates motion and animation in the product, from micro-interactions to transitions.", "doing": "Animating the onboarding transitions.", "with_designer": "Turns the interactions you design into smooth motion."}}'::jsonb),
  ('tech-lead', 'Tech Lead', 'role', 'engineering', null, 'Kỹ sư dẫn dắt kỹ thuật trong squad, chịu trách nhiệm giải pháp và chất lượng code.', 'Đang ước lượng effort cho story mới.', 'Cùng bạn và PM tạo thành product trio. Trả lời câu hỏi: làm được không, tốn bao lâu.', '["headset"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "The engineer who leads technical work in the squad and owns the solution and code quality.", "doing": "Estimating effort for a new story.", "with_designer": "Forms the product trio with you and the PM. Answers the questions: can we build it, and how long will it take?"}}'::jsonb),
  ('frontend-developer', 'Frontend Developer', 'role', 'engineering', 'https://academy.telos.vn/frontend-developer-la-ai-product/', 'Developer phụ trách giao diện người dùng, người biến file Figma thành sản phẩm chạy trên trình duyệt.', 'Đang dựng component Card theo file Figma của bạn.', 'Nhận handoff từ bạn. Sẽ hỏi về spacing, trạng thái và responsive.', '["laptop"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "The developer who builds the user interface, turning your Figma file into a product that runs in the browser.", "doing": "Building the Card component from your Figma file.", "with_designer": "Receives your handoff. Will ask about spacing, states and responsive behaviour."}}'::jsonb),
  ('backend-developer', 'Backend Developer', 'role', 'engineering', 'https://academy.telos.vn/backend-developer-la-ai-product/', 'Developer phụ trách logic, dữ liệu và API phía server.', 'Đang viết API lưu tiến độ onboarding.', 'Cho bạn biết dữ liệu nào có sẵn và hệ thống phản hồi nhanh tới đâu.', '["database"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "The developer behind server-side logic, data and APIs.", "doing": "Writing the API that saves onboarding progress.", "with_designer": "Tells you what data is available and how fast the system can respond."}}'::jsonb),
  ('fullstack-developer', 'Full-stack Developer', 'role', 'engineering', 'https://academy.telos.vn/full-stack-developer-la-ai-product/', 'Developer làm cả Frontend lẫn Backend, linh hoạt cho team cần tốc độ.', 'Đang làm landing page SEO từ đầu đến cuối.', 'Hay cùng bạn thử nhanh một ý tưởng trong vài ngày.', '["laptop"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "A developer who works on both frontend and backend, flexible for teams that need speed.", "doing": "Building an SEO landing page end to end.", "with_designer": "Often tries out an idea with you in just a few days."}}'::jsonb),
  ('mobile-developer', 'Mobile Developer', 'role', 'engineering', null, 'Developer làm ứng dụng iOS và Android.', 'Đang sửa lỗi cử chỉ vuốt trên Android.', 'Hỏi bạn về khác biệt pattern giữa iOS và Android.', '["phone"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "A developer building iOS and Android apps.", "doing": "Fixing a swipe gesture bug on Android.", "with_designer": "Asks you about pattern differences between iOS and Android."}}'::jsonb),
  ('qa-engineer', 'QA Engineer', 'role', 'engineering', null, 'Kỹ sư kiểm thử, đảm bảo sản phẩm chạy đúng trước khi ra mắt.', 'Đang viết test case cho luồng thanh toán.', 'So bản build với thiết kế của bạn và báo lại khi có chỗ lệch.', '["magnifier"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "A test engineer who makes sure the product works correctly before release.", "doing": "Writing test cases for the checkout flow.", "with_designer": "Compares the build against your design and flags anything that does not match."}}'::jsonb),
  ('software-architect', 'Software Architect', 'role', 'engineering', null, 'Người thiết kế kiến trúc tổng thể của hệ thống.', 'Đang vẽ sơ đồ tách dịch vụ thanh toán.', 'Ít làm trực tiếp, nhưng quyết định của họ ảnh hưởng tốc độ và giới hạn tính năng.', '["scroll"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Designs the overall architecture of the system.", "doing": "Diagramming how to split out the payment service.", "with_designer": "Rarely works with you directly, but their decisions affect speed and feature limits."}}'::jsonb),
  ('devops', 'DevOps & Platform Engineer', 'role', 'engineering', null, 'Xây hạ tầng và pipeline deploy, giữ hệ thống chạy ổn định.', 'Đang theo dõi bản deploy chiều nay.', 'Khi sản phẩm chậm hay sập, họ là người xử lý đầu tiên.', '["gear"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Builds the infrastructure and deploy pipelines, and keeps the system running.", "doing": "Watching this afternoon''s deploy.", "with_designer": "When the product is slow or goes down, they are the first to respond."}}'::jsonb),
  ('data-analyst', 'Data Analyst', 'role', 'data', null, 'Phân tích dữ liệu để trả lời câu hỏi về sản phẩm và kinh doanh.', 'Đang dựng funnel đăng ký của tuần này.', 'Cho bạn biết người dùng rời đi ở bước nào của luồng.', '["chart"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Analyses data to answer questions about the product and the business.", "doing": "Building this week''s sign-up funnel.", "with_designer": "Shows you at which step of a flow users drop off."}}'::jsonb),
  ('bi-analyst', 'Business Intelligence Analyst', 'role', 'data', null, 'Xây dashboard và báo cáo định kỳ cho các phòng ban.', 'Đang cập nhật dashboard doanh thu.', 'Dashboard của họ là nơi bạn tìm số liệu nhanh nhất.', '["pie"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Builds dashboards and recurring reports for every department.", "doing": "Updating the revenue dashboard.", "with_designer": "Their dashboards are the fastest place to find numbers."}}'::jsonb),
  ('data-scientist', 'Data Scientist', 'role', 'data', null, 'Xây mô hình dự đoán và gợi ý từ dữ liệu.', 'Đang huấn luyện mô hình gợi ý khoá học.', 'Cùng bạn thiết kế cách hiển thị gợi ý do AI tạo ra.', '["flask"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Builds prediction and recommendation models from data.", "doing": "Training the course recommendation model.", "with_designer": "Designs with you how AI-generated recommendations are shown."}}'::jsonb),
  ('data-engineer', 'Data Engineer', 'role', 'data', null, 'Xây đường ống dữ liệu để các nhóm khác dùng được dữ liệu.', 'Đang sửa pipeline đồng bộ dữ liệu đêm qua.', 'Ít làm trực tiếp, nhưng tracking bạn đề xuất cần họ để chạy.', '["database"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Builds the data pipelines that let other teams use data.", "doing": "Fixing last night''s data sync pipeline.", "with_designer": "Rarely works with you directly, but the tracking you propose needs them to run."}}'::jsonb),
  ('scrum-master', 'Scrum Master', 'role', 'delivery', null, 'Giữ nhịp Scrum: điều phối các buổi họp và gỡ vướng mắc cho team.', 'Đang chuẩn bị buổi Retro cuối sprint.', 'Giúp bạn gỡ những việc đang bị chặn trong sprint.', '["timer"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Keeps the Scrum rhythm: runs the ceremonies and clears blockers for the team.", "doing": "Preparing the end-of-sprint Retro.", "with_designer": "Helps you unblock work that is stuck in the sprint."}}'::jsonb),
  ('delivery-manager', 'Delivery Manager', 'role', 'delivery', null, 'Đảm bảo các team giao sản phẩm đúng hạn và phối hợp tốt với nhau.', 'Đang cập nhật kế hoạch phát hành.', 'Cho bạn biết hạn chót thật sự của một tính năng.', '["calendar"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Makes sure teams ship on time and coordinate well with each other.", "doing": "Updating the release plan.", "with_designer": "Tells you the real deadline for a feature."}}'::jsonb),
  ('project-manager', 'Project Manager', 'role', 'delivery', null, 'Quản lý dự án theo phạm vi, thời gian và nguồn lực.', 'Đang theo dõi tiến độ dự án tích hợp đối tác.', 'Cần bạn ước lượng thời gian thiết kế cho từng hạng mục.', '["calendar"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Manages projects by scope, time and resources.", "doing": "Tracking progress on the partner integration project.", "with_designer": "Needs you to estimate design time for each work item."}}'::jsonb),
  ('growth-manager', 'Growth Manager', 'role', 'business', null, 'Phụ trách tăng trưởng người dùng qua nhiều kênh marketing.', 'Đang lên chiến dịch giới thiệu bạn bè.', 'Cần bạn thiết kế landing page và luồng mời bạn bè.', '["megaphone"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Drives user growth across many marketing channels.", "doing": "Planning a refer-a-friend campaign.", "with_designer": "Needs you to design landing pages and the invite-a-friend flow."}}'::jsonb),
  ('performance-marketer', 'Performance Marketing Manager', 'role', 'business', null, 'Chạy quảng cáo trả phí và tối ưu chi phí trên mỗi người dùng.', 'Đang so sánh 3 mẫu banner quảng cáo.', 'Hay nhờ bạn làm biến thể banner và trang đích.', '["megaphone"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Runs paid ads and optimises the cost per user.", "doing": "Comparing 3 ad banner variants.", "with_designer": "Often asks you for banner variants and landing pages."}}'::jsonb),
  ('brand-manager', 'Brand Manager', 'role', 'business', null, 'Giữ gìn hình ảnh và giọng nói của thương hiệu.', 'Đang duyệt bộ nhận diện cho chiến dịch mới.', 'Bạn cần tuân theo guideline thương hiệu họ đặt ra.', '["flag"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Protects the brand''s image and voice.", "doing": "Approving the identity kit for a new campaign.", "with_designer": "You need to follow the brand guidelines they set."}}'::jsonb),
  ('content-marketer', 'Content Marketer', 'role', 'business', null, 'Viết nội dung cho blog, mạng xã hội và email.', 'Đang viết bài blog ra mắt tính năng.', 'Cần ảnh minh hoạ tính năng từ bạn.', '["pencil"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Writes content for the blog, social media and email.", "doing": "Writing the launch blog post for a feature.", "with_designer": "Needs feature illustrations from you."}}'::jsonb),
  ('crm-manager', 'CRM Manager', 'role', 'business', null, 'Quản lý email, thông báo và chương trình giữ chân khách hàng.', 'Đang thiết lập chuỗi email chào mừng.', 'Cùng bạn thiết kế email và thông báo trong app.', '["cards"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Manages email, notifications and customer retention programmes.", "doing": "Setting up the welcome email sequence.", "with_designer": "Designs emails and in-app messages with you."}}'::jsonb),
  ('seo-specialist', 'SEO Specialist', 'role', 'business', null, 'Tối ưu website để xuất hiện tốt trên Google.', 'Đang kiểm tra tốc độ tải trang.', 'Góp ý cấu trúc trang và tiêu đề khi bạn làm landing page.', '["magnifier"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Optimises the website to rank well on Google.", "doing": "Checking page load speed.", "with_designer": "Gives feedback on page structure and headings when you build landing pages."}}'::jsonb),
  ('csm', 'Customer Success Manager', 'role', 'business', null, 'Giúp khách hàng dùng sản phẩm thành công và gia hạn.', 'Đang gọi cho khách hàng sắp hết hạn.', 'Mang về phản hồi thật từ khách hàng cho bạn.', '["headset"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Helps customers succeed with the product and renew.", "doing": "Calling customers whose plans are about to expire.", "with_designer": "Brings real customer feedback back to you."}}'::jsonb),
  ('customer-support', 'Customer Support', 'role', 'business', null, 'Trả lời câu hỏi và xử lý sự cố của khách hàng.', 'Đang trả lời 12 ticket về quên mật khẩu.', 'Nguồn insight quý: lỗi nào người dùng hỏi nhiều nhất.', '["headset"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Answers customer questions and handles their problems.", "doing": "Answering 12 tickets about forgotten passwords.", "with_designer": "A valuable source of insight: which problems users ask about most."}}'::jsonb),
  ('account-manager', 'Account Manager', 'role', 'business', null, 'Quản lý quan hệ và hợp đồng với khách hàng lớn.', 'Đang chuẩn bị buổi demo cho khách hàng doanh nghiệp.', 'Cần bạn làm bản demo đẹp cho khách hàng lớn.', '["briefcase"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Manages relationships and contracts with large customers.", "doing": "Preparing a demo for an enterprise customer.", "with_designer": "Needs you to make a polished demo for big customers."}}'::jsonb),
  ('business-analyst', 'Business Analyst', 'role', 'business', 'https://academy.telos.vn/business-analyst-ba-la-gi-product-team/', 'Phân tích yêu cầu kinh doanh và dịch chúng thành đặc tả cho design và engineering.', 'Đang viết đặc tả yêu cầu cho tính năng hoá đơn.', 'Dịch yêu cầu kinh doanh thành đặc tả để bạn thiết kế.', '["clipboard"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Analyses business requirements and translates them into specifications for design and engineering.", "doing": "Writing the requirements spec for the invoicing feature.", "with_designer": "Translates business requirements into specs for you to design from."}}'::jsonb),
  ('stakeholder', 'Stakeholder', 'role', 'business', 'https://academy.telos.vn/stakeholder-la-ai-product/', 'Những người có lợi ích liên quan tới sản phẩm, có thể ảnh hưởng hoặc bị ảnh hưởng bởi quyết định thiết kế.', 'Đang chờ buổi Sprint Review để xem demo.', 'Bạn cần thuyết phục họ bằng lý do, dữ liệu và bản demo rõ ràng.', '["briefcase"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "People with a stake in the product, who can influence or be affected by design decisions.", "doing": "Waiting for the Sprint Review to see the demo.", "with_designer": "You need to convince them with reasons, data and a clear demo."}}'::jsonb),
  ('nhan-luu', 'Nhân Lưu', 'author', 'design', null, 'Cha nội này là Academic Director tại TELOS Academy và là tác giả của trò chơi này. Ổng đi khắp các phòng để kể chuyện cười không vui làm giảm năng suất làm việc của mọi người.', 'Đang đi một vòng văn phòng, hỏi thăm từng team.', 'Ổng có thể chỉ cho bạn lộ trình học UI/UX và hướng phát triển trong lĩnh vực này.', '["blazer", "glasses", "necklace", "laptopCarry"]'::jsonb, '{"dark": false, "outfit": {"legs": "#C9BA95", "feet": "#B48D5C"}}'::jsonb, 'Academic Director · TELOS Academy', '[{"label": "Nhận quà", "url": "https://nhanluu.com/contact/", "primary": true}, {"label": "Tìm hiểu thêm", "url": "https://nhanluu.com"}]'::jsonb, true, '{"en": {"summary": "This guy is the Academic Director at TELOS Academy and the author of this game. He wanders from room to room telling unfunny jokes that lower everyone''s productivity.", "doing": "Walking around the office, checking in on every team.", "with_designer": "He can show you a learning path for UI/UX and where to grow in this field.", "tag": "Academic Director · TELOS Academy", "cta": ["Get a gift", "Learn more"]}}'::jsonb),
  ('user', 'User', 'guest', 'business', null, 'Người dùng thật của sản phẩm. Bạn ấy không quan tâm team làm việc ra sao, chỉ quan tâm sản phẩm có dễ dùng hay không.', 'Đang ngồi bấm điện thoại, lướt thử ứng dụng.', 'Hỏi và quan sát người dùng thật là cách nhanh nhất để biết thiết kế của bạn có dùng được không.', '["phoneUse"]'::jsonb, '{"dark": true, "outfit": null}'::jsonb, 'Người dùng thật', '[{"label": "Usability Testing", "url": "https://academy.telos.vn/usability-testing-la-gi-ux-design/", "primary": true}, {"label": "Learnability", "url": "https://academy.telos.vn/learnability-la-gi-ux-design/", "primary": false}]'::jsonb, true, '{"en": {"summary": "A real user of the product. They don''t care how the team works, only whether the product is easy to use.", "doing": "Tapping away on their phone, trying out the app.", "with_designer": "Asking and watching real users is the fastest way to know whether your design actually works.", "tag": "Real user", "cta": ["Usability Testing", "Learnability"]}}'::jsonb),
  ('client', 'Client', 'role', 'business', null, 'Khách hàng thuê agency làm sản phẩm. Họ trả tiền, đặt mục tiêu và là người quyết định cuối cùng, nhưng họ không phải người dùng của sản phẩm.', 'Đang ngồi chờ buổi họp, tranh thủ trả lời tin nhắn công việc.', 'Bạn trình bày thiết kế cho họ và nghe phản hồi. Mọi yêu cầu mới của họ phải đi qua Account Manager và Project Manager.', '["briefcase"]'::jsonb, '{"dark": false, "outfit": null, "body_color": "#FFC53D", "outline_color": "#8A5D00"}'::jsonb, 'Khách hàng của agency', null, true, '{"en": {"summary": "The customer who hires the agency to build their product. They pay, set the goals and have the final say, but they are not the product''s users.", "doing": "Waiting for the meeting while answering work messages.", "with_designer": "You present designs to them and listen to their feedback. Every new request from them must go through the Account Manager and the Project Manager.", "tag": "The agency''s client"}}'::jsonb),
  ('design-director', 'Design Director', 'role', 'design', null, 'Người chịu trách nhiệm về chất lượng thiết kế của cả agency. Mọi bản thiết kế phải qua Design Director trước khi gửi khách.', 'Đang xem lại concept của ba dự án khác nhau.', 'Quản lý chuyên môn trực tiếp của bạn. Duyệt thiết kế, góp ý và quyết định bản nào đủ tốt để gửi khách.', '["glasses", "pointer"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Responsible for the design quality of the whole agency. Every design has to pass the Design Director before it goes to a client.", "doing": "Reviewing concepts for three different projects.", "with_designer": "Your direct craft manager. Approves designs, gives feedback and decides which version is good enough to send to the client."}}'::jsonb),
  ('graphic-designer', 'Graphic Designer', 'role', 'design', null, 'Designer làm nhận diện thương hiệu, banner, hình minh hoạ và ấn phẩm truyền thông.', 'Đang chỉnh bộ banner cho chiến dịch khai trương của khách.', 'Cho bạn biết màu, font và hình ảnh thương hiệu của khách để giao diện không lệch nhận diện.', '["palette"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "A designer who works on brand identity, banners, illustrations and marketing materials.", "doing": "Adjusting the banner set for a client''s grand opening campaign.", "with_designer": "Tells you the client''s brand colours, fonts and imagery so the interface stays on brand."}}'::jsonb),
  ('sales', 'Sales / Business Developer', 'role', 'business', null, 'Người đi tìm khách hàng và mang dự án về cho agency.', 'Đang chuẩn bị slide cho buổi gặp khách chiều nay.', 'Hay nhờ bạn dựng nhanh một bản demo để khách dễ hình dung trước khi ký hợp đồng.', '["megaphone"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "Finds clients and brings projects into the agency.", "doing": "Preparing slides for this afternoon''s client meeting.", "with_designer": "Often asks you to put together a quick demo so the client can picture the product before signing."}}'::jsonb),
  ('freelancer', 'Freelancer', 'role', 'design', 'https://academy.telos.vn/cach-lam-freelance-thiet-ke-giao-dien/', 'Designer làm việc độc lập, được agency thuê theo từng dự án khi team thiếu người.', 'Đang làm bộ icon cho một dự án cần gấp trong tuần này.', 'Làm cùng bạn trong vài tuần rồi rời đi. Bạn cần bàn giao file gọn gàng để họ vào việc nhanh.', '["laptop", "backpack"]'::jsonb, '{"dark": false, "outfit": null}'::jsonb, null, null, true, '{"en": {"summary": "An independent designer the agency hires per project when the team is short on people.", "doing": "Making an icon set for a project that is due this week.", "with_designer": "Works with you for a few weeks and then leaves. Hand over clean files so they can get going fast."}}'::jsonb)
on conflict (id) do update set title = excluded.title, kind = excluded.kind, "group" = excluded."group", article_url = excluded.article_url, summary = excluded.summary, doing = excluded.doing, with_designer = excluded.with_designer, props = excluded.props, appearance = excluded.appearance, tag = excluded.tag, cta = excluded.cta, is_active = excluded.is_active, i18n = excluded.i18n;

-- lượt 2: báo cáo cho ai
update tm_characters c set reports_to = v.rt, reports_to_small = v.rts, reports_to_agency = v.rta from (values
  ('ceo', null, null, null),
  ('cpo', 'ceo', null, null),
  ('cto', 'ceo', null, null),
  ('head-of-design', 'cpo', null, null),
  ('head-of-data', 'cpo', null, null),
  ('head-of-eng', 'cto', null, null),
  ('product-manager', 'cpo', 'ceo', null),
  ('product-owner', 'cpo', null, null),
  ('growth-pm', 'cpo', null, null),
  ('data-pm', 'cpo', null, null),
  ('ui-ux-designer', 'design-manager', 'product-manager', 'design-director'),
  ('product-designer', 'design-manager', null, null),
  ('ui-designer', 'design-manager', null, null),
  ('ux-designer', 'design-manager', null, null),
  ('intern', 'ui-ux-designer', null, 'ui-ux-designer'),
  ('ds-designer', 'head-of-design', null, null),
  ('ux-design-engineer', 'head-of-design', null, null),
  ('design-manager', 'head-of-design', null, null),
  ('ux-researcher', 'head-of-design', null, null),
  ('ux-writer', 'head-of-design', null, null),
  ('motion-designer', 'head-of-design', null, null),
  ('tech-lead', 'head-of-eng', 'ceo', 'ceo'),
  ('frontend-developer', 'head-of-eng', 'tech-lead', 'tech-lead'),
  ('backend-developer', 'head-of-eng', 'tech-lead', 'tech-lead'),
  ('fullstack-developer', 'head-of-eng', null, null),
  ('mobile-developer', 'head-of-eng', 'tech-lead', null),
  ('qa-engineer', 'head-of-eng', 'tech-lead', 'tech-lead'),
  ('software-architect', 'cto', null, null),
  ('devops', 'cto', null, null),
  ('data-analyst', 'head-of-data', null, null),
  ('bi-analyst', 'head-of-data', null, null),
  ('data-scientist', 'head-of-data', null, null),
  ('data-engineer', 'head-of-data', null, null),
  ('scrum-master', 'delivery-manager', null, null),
  ('delivery-manager', 'cto', null, null),
  ('project-manager', 'delivery-manager', null, 'ceo'),
  ('growth-manager', 'ceo', 'ceo', null),
  ('performance-marketer', 'growth-manager', null, null),
  ('brand-manager', 'ceo', null, null),
  ('content-marketer', 'growth-manager', null, null),
  ('crm-manager', 'growth-manager', null, null),
  ('seo-specialist', 'growth-manager', null, null),
  ('csm', 'ceo', null, null),
  ('customer-support', 'csm', 'ceo', null),
  ('account-manager', 'ceo', 'ceo', 'ceo'),
  ('business-analyst', 'cpo', 'ceo', 'project-manager'),
  ('stakeholder', null, null, null),
  ('nhan-luu', null, null, null),
  ('user', null, null, null),
  ('client', null, null, null),
  ('design-director', null, null, 'ceo'),
  ('graphic-designer', null, null, 'design-director'),
  ('sales', null, null, 'ceo'),
  ('freelancer', null, null, 'design-director')
) as v(id, rt, rts, rta) where c.id = v.id;

-- 3. Vị trí (fixed = ngồi cố định, không đi dạo, không tới điểm tập hợp)
insert into tm_placements (id, character_id, scale, room_id, seat_order, fixed) values
  ('product-manager@P1', 'product-manager', 'small', 'P1', 0, false),
  ('ui-ux-designer@P1', 'ui-ux-designer', 'small', 'P1', 1, false),
  ('intern@P1', 'intern', 'small', 'P1', 2, false),
  ('tech-lead@P2', 'tech-lead', 'small', 'P2', 0, false),
  ('frontend-developer@P2', 'frontend-developer', 'small', 'P2', 1, false),
  ('backend-developer@P2', 'backend-developer', 'small', 'P2', 2, false),
  ('mobile-developer@P2', 'mobile-developer', 'small', 'P2', 3, false),
  ('qa-engineer@P2', 'qa-engineer', 'small', 'P2', 4, false),
  ('ceo@P3', 'ceo', 'small', 'P3', 0, false),
  ('growth-manager@P3', 'growth-manager', 'small', 'P3', 1, false),
  ('account-manager@P3', 'account-manager', 'small', 'P3', 2, false),
  ('customer-support@P3', 'customer-support', 'small', 'P3', 3, false),
  ('business-analyst@P3', 'business-analyst', 'small', 'P3', 4, false),
  ('ceo@R01', 'ceo', 'large', 'R01', 0, false),
  ('cpo@R01', 'cpo', 'large', 'R01', 1, false),
  ('cto@R01', 'cto', 'large', 'R01', 2, false),
  ('head-of-design@R01', 'head-of-design', 'large', 'R01', 3, false),
  ('head-of-data@R01', 'head-of-data', 'large', 'R01', 4, false),
  ('head-of-eng@R01', 'head-of-eng', 'large', 'R01', 5, false),
  ('data-pm@R07', 'data-pm', 'large', 'R07', 0, false),
  ('data-analyst@R07', 'data-analyst', 'large', 'R07', 1, false),
  ('bi-analyst@R07', 'bi-analyst', 'large', 'R07', 2, false),
  ('data-scientist@R07', 'data-scientist', 'large', 'R07', 3, false),
  ('data-engineer@R07', 'data-engineer', 'large', 'R07', 4, false),
  ('stakeholder@R08', 'stakeholder', 'large', 'R08', 0, false),
  ('growth-pm@R02', 'growth-pm', 'large', 'R02', 0, false),
  ('product-designer@R02', 'product-designer', 'large', 'R02', 1, false),
  ('tech-lead@R02', 'tech-lead', 'large', 'R02', 2, false),
  ('fullstack-developer@R02', 'fullstack-developer', 'large', 'R02', 3, false),
  ('qa-engineer@R02', 'qa-engineer', 'large', 'R02', 4, false),
  ('product-owner@R02', 'product-owner', 'large', 'R02', 5, false),
  ('product-manager@R03', 'product-manager', 'large', 'R03', 0, false),
  ('ui-ux-designer@R03', 'ui-ux-designer', 'large', 'R03', 1, false),
  ('ui-designer@R03', 'ui-designer', 'large', 'R03', 2, false),
  ('intern@R03', 'intern', 'large', 'R03', 3, false),
  ('tech-lead@R03', 'tech-lead', 'large', 'R03', 4, false),
  ('frontend-developer@R03', 'frontend-developer', 'large', 'R03', 5, false),
  ('mobile-developer@R03', 'mobile-developer', 'large', 'R03', 6, false),
  ('backend-developer@R03', 'backend-developer', 'large', 'R03', 7, false),
  ('qa-engineer@R03', 'qa-engineer', 'large', 'R03', 8, false),
  ('product-manager@R04', 'product-manager', 'large', 'R04', 0, false),
  ('ux-designer@R04', 'ux-designer', 'large', 'R04', 1, false),
  ('tech-lead@R04', 'tech-lead', 'large', 'R04', 2, false),
  ('backend-developer@R04', 'backend-developer', 'large', 'R04', 3, false),
  ('frontend-developer@R04', 'frontend-developer', 'large', 'R04', 4, false),
  ('software-architect@R05', 'software-architect', 'large', 'R05', 0, false),
  ('devops@R05', 'devops', 'large', 'R05', 1, false),
  ('ds-designer@R05', 'ds-designer', 'large', 'R05', 2, false),
  ('ux-design-engineer@R05', 'ux-design-engineer', 'large', 'R05', 3, false),
  ('design-manager@R06', 'design-manager', 'large', 'R06', 0, false),
  ('ux-researcher@R06', 'ux-researcher', 'large', 'R06', 1, false),
  ('ux-writer@R06', 'ux-writer', 'large', 'R06', 2, false),
  ('motion-designer@R06', 'motion-designer', 'large', 'R06', 3, false),
  ('scrum-master@R09', 'scrum-master', 'large', 'R09', 0, false),
  ('delivery-manager@R09', 'delivery-manager', 'large', 'R09', 1, false),
  ('project-manager@R09', 'project-manager', 'large', 'R09', 2, false),
  ('growth-manager@R10', 'growth-manager', 'large', 'R10', 0, false),
  ('performance-marketer@R10', 'performance-marketer', 'large', 'R10', 1, false),
  ('brand-manager@R10', 'brand-manager', 'large', 'R10', 2, false),
  ('content-marketer@R10', 'content-marketer', 'large', 'R10', 3, false),
  ('crm-manager@R10', 'crm-manager', 'large', 'R10', 4, false),
  ('seo-specialist@R10', 'seo-specialist', 'large', 'R10', 5, false),
  ('csm@R10', 'csm', 'large', 'R10', 6, false),
  ('customer-support@R10', 'customer-support', 'large', 'R10', 7, false),
  ('account-manager@R10', 'account-manager', 'large', 'R10', 8, false),
  ('business-analyst@R10', 'business-analyst', 'large', 'R10', 9, false),
  ('user@P5', 'user', 'small', 'P5', 0, true),
  ('nhan-luu@P5', 'nhan-luu', 'small', 'P5', null, false),
  ('user@R11', 'user', 'large', 'R11', 0, true),
  ('nhan-luu@R11', 'nhan-luu', 'large', 'R11', null, false),
  ('design-director@A1', 'design-director', 'agency', 'A1', 0, false),
  ('ui-ux-designer@A1', 'ui-ux-designer', 'agency', 'A1', 1, false),
  ('graphic-designer@A1', 'graphic-designer', 'agency', 'A1', 2, false),
  ('intern@A1', 'intern', 'agency', 'A1', 3, false),
  ('freelancer@A1', 'freelancer', 'agency', 'A1', 4, false),
  ('tech-lead@A2', 'tech-lead', 'agency', 'A2', 0, false),
  ('frontend-developer@A2', 'frontend-developer', 'agency', 'A2', 1, false),
  ('backend-developer@A2', 'backend-developer', 'agency', 'A2', 2, false),
  ('qa-engineer@A2', 'qa-engineer', 'agency', 'A2', 3, false),
  ('account-manager@A3', 'account-manager', 'agency', 'A3', 0, false),
  ('project-manager@A3', 'project-manager', 'agency', 'A3', 1, false),
  ('business-analyst@A3', 'business-analyst', 'agency', 'A3', 2, false),
  ('client@A4', 'client', 'agency', 'A4', 0, true),
  ('sales@A6', 'sales', 'agency', 'A6', 0, false),
  ('ceo@A6', 'ceo', 'agency', 'A6', 1, false),
  ('user@A5', 'user', 'agency', 'A5', 0, true),
  ('nhan-luu@A5', 'nhan-luu', 'agency', 'A5', null, false)
on conflict (id) do update set character_id = excluded.character_id, scale = excluded.scale, room_id = excluded.room_id, seat_order = excluded.seat_order, fixed = excluded.fixed;

-- 4. Nhiệm vụ
insert into tm_quests (id, type, scale, sort_order, title, room_id, giver, gather, offer_text, done_text, rewards, is_active, daily_date, i18n) values
  ('small-01', 'main', 'small', 1, 'Nhận việc đầu sprint', 'P4', 'product-manager@P1', '["tech-lead@P2", "frontend-developer@P2"]'::jsonb, 'Chào bạn! Sprint này mình làm lại luồng onboarding. Trước khi vẽ, bạn hỏi Tech Lead xem phần nào khó làm nhé.', 'Tuyệt, wireframe rõ ràng. Bước ảnh đại diện để sprint sau.', '[{"type": "character", "id": "product-manager"}, {"type": "term", "name": "Agile", "url": "https://academy.telos.vn/waterfall-va-agile-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "Picking up work at sprint start", "offer_text": "Hi! This sprint we''re redoing the onboarding flow. Before you start drawing, ask the Tech Lead which parts are hard to build.", "done_text": "Great, the wireframe is clear. We''ll leave the profile photo step for next sprint."}}'::jsonb),
  ('small-02', 'main', 'small', 2, 'Hiểu mục tiêu kinh doanh', 'P3', 'ceo@P3', '["business-analyst@P3"]'::jsonb, 'Quý này công ty cần tăng 20% người dùng trả phí. Bạn hỏi BA xem onboarding liên quan thế nào.', 'Đúng rồi. Thiết kế nào giúp người dùng thấy giá trị sớm là thiết kế tốt.', '[{"type": "character", "id": "business-analyst"}, {"type": "term", "name": "Viability", "url": "https://academy.telos.vn/viability-la-gi-product-design/"}]'::jsonb, true, null, '{"en": {"title": "Understanding the business goal", "offer_text": "This quarter the company needs 20% more paying users. Ask the BA how onboarding ties into that.", "done_text": "Exactly. A design that helps users see value early is a good design."}}'::jsonb),
  ('small-03', 'main', 'small', 3, 'Nghe tiếng nói khách hàng', 'P3', 'customer-support@P3', '["account-manager@P3"]'::jsonb, 'Mình nhận rất nhiều câu hỏi về bước đăng ký. Bạn sang hỏi Account Manager thêm góc nhìn khách lớn nhé.', 'Bạn ghi lại hai insight này vào persona nhé. Cảm ơn bạn đã lắng nghe!', '[{"type": "term", "name": "User Persona", "url": "https://academy.telos.vn/user-persona-la-gi-cach-tao-ra-1-user-persona/"}, {"type": "term", "name": "Empathy Map", "url": "https://academy.telos.vn/huong-dan-nguoi-moi-ve-empathy-map-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "Listening to customers", "offer_text": "We get a lot of questions about the sign-up step. Go ask the Account Manager for the big customers'' point of view too.", "done_text": "Add these two insights to the persona. Thanks for listening!"}}'::jsonb),
  ('small-04', 'main', 'small', 4, 'Handoff cho Dev team', 'P2', 'frontend-developer@P2', '["qa-engineer@P2", "mobile-developer@P2"]'::jsonb, 'File Figma xong rồi hả? Trước khi code, bạn giải thích các trạng thái lỗi cho QA giúp mình.', 'Cảm ơn bạn. Có prototype bấm thử được nên mình hiểu luồng nhanh hơn nhiều.', '[{"type": "character", "id": "frontend-developer"}, {"type": "term", "name": "Prototype", "url": "https://academy.telos.vn/prototype-la-gi-video-huong-dan/"}]'::jsonb, true, null, '{"en": {"title": "Handoff to the Dev team", "offer_text": "Is the Figma file done? Before we code, please walk QA through the error states.", "done_text": "Thank you. With a clickable prototype I understood the flow much faster."}}'::jsonb),
  ('small-05', 'main', 'small', 5, 'Demo cuối sprint', 'P4', 'product-manager@P1', '["ceo@P3", "growth-manager@P3", "tech-lead@P2", "customer-support@P3"]'::jsonb, 'Đến giờ demo rồi! Cả công ty đang ở phòng họp. Bạn trình bày rồi hỏi ý kiến CEO nhé.', 'Sprint đầu tiên của bạn hoàn thành rồi. Chào mừng tới team!', '[{"type": "character", "id": "stakeholder"}, {"type": "term", "name": "Desirability", "url": "https://academy.telos.vn/desirability-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "End-of-sprint demo", "offer_text": "Demo time! The whole company is in the meeting room. Present your work, then ask the CEO for feedback.", "done_text": "Your first sprint is done. Welcome to the team!"}}'::jsonb),
  ('large-01', 'main', 'large', 1, 'Sprint Planning', 'R08', 'product-manager@R03', '["tech-lead@R03", "frontend-developer@R03", "qa-engineer@R03"]'::jsonb, 'Sprint này squad Core làm lại luồng onboarding. Bạn hỏi Tech Lead ước lượng effort cho phần thiết kế mới nhé.', 'Ok, mình chốt story này vào sprint. Nhớ ghé team Design System nhé.', '[{"type": "character", "id": "product-manager"}, {"type": "term", "name": "Agile", "url": "https://academy.telos.vn/waterfall-va-agile-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "Sprint Planning", "offer_text": "This sprint the Core squad is redoing the onboarding flow. Ask the Tech Lead to estimate the effort for the new design.", "done_text": "OK, I''m putting this story into the sprint. Remember to drop by the Design System team."}}'::jsonb),
  ('large-02', 'main', 'large', 2, 'Discovery cùng số liệu', 'R03', 'tech-lead@R03', '["product-manager@R03"]'::jsonb, 'Trước khi vẽ, mình cần biết người dùng rơi ở bước nào. Bạn sang Data & Analytics xin số liệu funnel nhé.', '42% là con số lớn. Vấn đề rõ rồi, giờ mới tới giải pháp.', '[{"type": "term", "name": "Problem Statement", "url": "https://academy.telos.vn/problem-statement-cach-xac-dinh-cho-nguoi-moi-hoc-ui-ux/"}, {"type": "term", "name": "Customer Journey Map", "url": "https://academy.telos.vn/customer-journey-map-hanh-trinh-khach-hang/"}]'::jsonb, true, null, '{"en": {"title": "Discovery with data", "offer_text": "Before drawing, we need to know where users drop off. Go to Data & Analytics and ask for the funnel numbers.", "done_text": "42% is a big number. The problem is clear now, only then do we move to solutions."}}'::jsonb),
  ('large-03', 'main', 'large', 3, 'Kiểm tra component', 'R05', 'ds-designer@R05', '["ux-design-engineer@R05"]'::jsonb, 'Bạn định vẽ thẻ chọn sở thích mới à? Hỏi UX Design Engineer xem component Chip đã có những gì đã.', 'Vậy mình thêm một biến thể thay vì làm component mới. Cảm ơn bạn đã hỏi trước!', '[{"type": "character", "id": "ds-designer"}, {"type": "term", "name": "Design System", "url": "https://academy.telos.vn/design-system-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "Checking the components", "offer_text": "Planning to draw a new interest-picker card? Ask the UX Design Engineer what the Chip component already has.", "done_text": "So we add a variant instead of a new component. Thanks for asking first!"}}'::jsonb),
  ('large-04', 'main', 'large', 4, 'Design Critique', 'R06', 'design-manager@R06', '["product-designer@R02", "ui-designer@R03", "ux-designer@R04"]'::jsonb, 'Chiều nay đến lượt bạn trình bày wireframe. Lấy góp ý từ Product Designer và UX Designer nhé.', 'Hai góp ý rất tốt. Critique là để thiết kế tốt hơn, không phải để chấm điểm bạn.', '[{"type": "term", "name": "Heuristic Evaluation", "url": "https://academy.telos.vn/phuong-phap-heuristic-evaluation/"}, {"type": "term", "name": "Wireframe", "url": "https://academy.telos.vn/wireframe-khung-xuong-cua-thiet-ke/"}]'::jsonb, true, null, '{"en": {"title": "Design Critique", "offer_text": "This afternoon it''s your turn to present your wireframes. Get feedback from the Product Designer and the UX Designer.", "done_text": "Two great pieces of feedback. Critique is there to make the design better, not to grade you."}}'::jsonb),
  ('large-05', 'main', 'large', 5, 'Usability Test', 'R11', 'ux-researcher@R06', '["product-manager@R03"]'::jsonb, 'Mình mời được một người dùng thật, bạn ấy đang ngồi ở Pantry. Bạn cùng mình hỏi bạn ấy thử luồng onboarding nhé.', 'Một vấn đề thật, từ người dùng thật. Bạn sửa độ tương phản nút đó trước khi handoff nhé.', '[{"type": "term", "name": "Usability Testing", "url": "https://academy.telos.vn/usability-testing-la-gi-ux-design/"}, {"type": "term", "name": "Usability", "url": "https://academy.telos.vn/usability-la-gi-ux-design/"}]'::jsonb, true, null, '{"en": {"title": "Usability Test", "offer_text": "I''ve invited a real user, they''re sitting in the Pantry. Let''s ask them to try the onboarding flow together.", "done_text": "A real problem, from a real user. Fix that button''s contrast before handoff."}}'::jsonb),
  ('large-06', 'main', 'large', 6, 'Handoff', 'R03', 'frontend-developer@R03', '["qa-engineer@R03", "mobile-developer@R03"]'::jsonb, 'File xong chưa? Bạn giải thích trạng thái lỗi và trạng thái tải cho QA giúp mình.', 'Có prototype bấm thử nên cả team hiểu luồng rất nhanh. Cảm ơn bạn!', '[{"type": "character", "id": "frontend-developer"}, {"type": "term", "name": "Prototype", "url": "https://academy.telos.vn/prototype-la-gi-video-huong-dan/"}]'::jsonb, true, null, '{"en": {"title": "Handoff", "offer_text": "Is the file ready? Please walk QA through the error and loading states.", "done_text": "With a clickable prototype the whole team got the flow really fast. Thank you!"}}'::jsonb),
  ('large-07', 'main', 'large', 7, 'Sprint Review', 'R08', 'product-manager@R03', '["growth-manager@R10", "csm@R10", "stakeholder@R08", "tech-lead@R03"]'::jsonb, 'Đến giờ demo rồi. Marketing và Customer Success đều tới. Bạn nghe phản hồi từ hai bên nhé.', 'Hai ý này mình đưa vào backlog sprint sau. Demo của bạn rất thuyết phục.', '[{"type": "character", "id": "stakeholder"}, {"type": "term", "name": "Desirability", "url": "https://academy.telos.vn/desirability-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "Sprint Review", "offer_text": "Demo time. Marketing and Customer Success are both here. Listen to feedback from both sides.", "done_text": "I''ll put both ideas into next sprint''s backlog. Your demo was very convincing."}}'::jsonb),
  ('large-08', 'main', 'large', 8, '1-on-1 cuối sprint', 'R06', 'design-manager@R06', '[]'::jsonb, 'Sprint vừa rồi bạn đã làm việc với gần như mọi phòng ban. Mình nói chuyện về mục tiêu phát triển của bạn nhé.', 'Mục tiêu quý tới: tự dẫn một buổi Critique và bắt đầu làm portfolio từ dự án này.', '[{"type": "character", "id": "product-designer"}, {"type": "term", "name": "Portfolio", "url": "https://academy.telos.vn/product-designer-portfolio-gom-gi/"}]'::jsonb, true, null, '{"en": {"title": "End-of-sprint 1-on-1", "offer_text": "This sprint you worked with almost every department. Let''s talk about your growth goals.", "done_text": "Goals for next quarter: run a Critique session yourself and start a portfolio piece from this project."}}'::jsonb),
  ('agency-01', 'main', 'agency', 1, 'Làm demo để chốt hợp đồng', 'A6', 'sales@A6', '["ceo@A6"]'::jsonb, 'Chiều nay mình đi gặp một chuỗi phòng gym, họ muốn làm app đặt lịch tập. Bạn dựng giúp mình một màn hình demo nhé. Không cần hoàn chỉnh, miễn là khách hình dung được.', 'Chốt được rồi! Khách ký hợp đồng 8 tuần. Tuần sau kickoff, bạn vào dự án này nhé.', '[{"type": "term", "name": "Mockup", "url": "https://academy.telos.vn/mockup-la-gi-huong-dan-toan-tap-cho-nguoi-moi/"}, {"type": "term", "name": "Portfolio", "url": "https://academy.telos.vn/product-designer-portfolio-gom-gi/"}]'::jsonb, true, null, '{"en": {"title": "A demo to close the deal", "offer_text": "This afternoon I''m meeting a gym chain that wants a class-booking app. Can you put together one demo screen for me? It doesn''t need to be complete, just enough for the client to picture it.", "done_text": "We closed it! The client signed an 8-week contract. Kickoff is next week and you''re on this project."}}'::jsonb),
  ('agency-02', 'main', 'agency', 2, 'Kickoff và nhận brief', 'A4', 'account-manager@A3', '["project-manager@A3"]'::jsonb, 'Hôm nay kickoff với khách. Bạn đừng vội nói về giao diện. Hãy hỏi xem họ muốn đạt điều gì và hội viên của họ là ai.', 'Hỏi hay lắm. Biết mục tiêu của khách rồi thì sau này mình có cơ sở để từ chối những yêu cầu lạc đề.', '[{"type": "character", "id": "stakeholder"}, {"type": "term", "name": "Problem Statement", "url": "https://academy.telos.vn/problem-statement-cach-xac-dinh-cho-nguoi-moi-hoc-ui-ux/"}]'::jsonb, true, null, '{"en": {"title": "Kickoff and the brief", "offer_text": "Kickoff with the client is today. Don''t jump into the interface yet. Ask what they want to achieve and who their members are.", "done_text": "Great questions. Now that we know the client''s goal, we have grounds to say no to off-topic requests later."}}'::jsonb),
  ('agency-03', 'main', 'agency', 3, 'Chốt phạm vi dự án', 'A3', 'project-manager@A3', '["business-analyst@A3"]'::jsonb, 'Hợp đồng là 8 tuần với ngân sách cố định. Bạn hỏi BA danh sách màn hình, rồi sang hỏi Tech Lead xem làm kịp không.', 'Vậy giai đoạn 1 là 9 màn hình, chưa có thanh toán. Mình ghi rõ vào biên bản để sau này không ai tranh cãi.', '[{"type": "character", "id": "business-analyst"}, {"type": "term", "name": "MVP", "url": "https://academy.telos.vn/mo-hinh-mvp-trong-hoc-ui-ux-hoc-cach-hoan-thanh/"}, {"type": "term", "name": "Feasibility", "url": "https://academy.telos.vn/feasibility-la-gi-product-design/"}]'::jsonb, true, null, '{"en": {"title": "Locking the project scope", "offer_text": "The contract is 8 weeks with a fixed budget. Ask the BA for the list of screens, then ask the Tech Lead whether we can make it in time.", "done_text": "So phase 1 is 9 screens, no payments yet. I''ll write it into the minutes so nobody argues about it later."}}'::jsonb),
  ('agency-04', 'main', 'agency', 4, 'Duyệt nội bộ', 'A1', 'design-director@A1', '["graphic-designer@A1"]'::jsonb, 'Trước khi gửi khách, mọi thứ phải qua mình. Bạn làm concept cho luồng đặt lịch rồi mang lại đây.', 'Luồng 3 bước rõ ràng. Sửa lại độ tương phản chữ trên nền cam rồi gửi khách được. Nhớ nhé: khách chỉ nên thấy bản đã duyệt nội bộ.', '[{"type": "term", "name": "Wireframe", "url": "https://academy.telos.vn/wireframe-khung-xuong-cua-thiet-ke/"}, {"type": "term", "name": "Heuristic Evaluation", "url": "https://academy.telos.vn/phuong-phap-heuristic-evaluation/"}]'::jsonb, true, null, '{"en": {"title": "Internal review", "offer_text": "Before anything goes to the client, it goes through me. Make a concept for the booking flow and bring it here.", "done_text": "A clear 3-step flow. Fix the text contrast on the orange background and it can go to the client. Remember: clients should only see work that passed internal review."}}'::jsonb),
  ('agency-05', 'main', 'agency', 5, 'Trình bày cho khách hàng', 'A4', 'account-manager@A3', '["design-director@A1", "project-manager@A3"]'::jsonb, 'Khách tới rồi. Bạn trình bày concept nhé. Nhớ bắt đầu từ mục tiêu của họ, đừng bắt đầu từ màu sắc.', 'Khách thích luồng chính là thắng lớn rồi. Mấy thứ khách đòi thêm thì đừng gật ngay, để mình và PM xem lại hợp đồng đã.', '[{"type": "term", "name": "Prototype", "url": "https://academy.telos.vn/prototype-la-gi-video-huong-dan/"}, {"type": "term", "name": "Desirability", "url": "https://academy.telos.vn/desirability-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "Presenting to the client", "offer_text": "The client is here. Present your concept. Remember to start from their goals, not from the colours.", "done_text": "The client likes the main flow, that''s a big win. Don''t say yes right away to the extras they asked for, let me and the PM check the contract first."}}'::jsonb),
  ('agency-06', 'main', 'agency', 6, 'Khách hàng đổi ý', 'A4', 'client@A4', '[]'::jsonb, 'À em ơi, tiện thể làm luôn cho anh phần bán gói tập online với tích điểm đổi quà nhé. Chắc thêm vài màn hình thôi mà.', 'Ừ, anh hiểu rồi. Vậy cứ làm xong giai đoạn 1 đã, phần kia bên em báo giá sau nhé.', '[{"type": "term", "name": "Viability", "url": "https://academy.telos.vn/viability-la-gi-product-design/"}, {"type": "term", "name": "Agile", "url": "https://academy.telos.vn/waterfall-va-agile-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "The client changes their mind", "offer_text": "Oh, while you''re at it, can you also add online class packages and a points-for-rewards scheme? Should only be a few more screens.", "done_text": "OK, I get it. Let''s finish phase 1 first, and your team can send me a quote for the rest later."}}'::jsonb),
  ('agency-07', 'main', 'agency', 7, 'Thuyết phục bằng người dùng', 'A3', 'project-manager@A3', '["account-manager@A3"]'::jsonb, 'Khách vẫn muốn nhồi banner lên trang chủ. Cãi bằng ý kiến cá nhân thì mình thua. Bạn ra Pantry cho một hội viên dùng thử rồi mang kết quả về.', 'Thấy chưa, khách không nghe designer nhưng nghe người dùng của họ. Lần sau cứ test trước khi tranh luận.', '[{"type": "term", "name": "Usability Testing", "url": "https://academy.telos.vn/usability-testing-la-gi-ux-design/"}, {"type": "term", "name": "User Persona", "url": "https://academy.telos.vn/user-persona-la-gi-cach-tao-ra-1-user-persona/"}]'::jsonb, true, null, '{"en": {"title": "Winning the argument with users", "offer_text": "The client still wants to stuff banners onto the home screen. If we argue with personal opinions, we lose. Go to the Pantry, have a member try it, and bring back the results.", "done_text": "See? The client doesn''t listen to designers, but they do listen to their users. Next time, test before you argue."}}'::jsonb),
  ('agency-08', 'main', 'agency', 8, 'Handoff và nghiệm thu', 'A2', 'tech-lead@A2', '["frontend-developer@A2", "qa-engineer@A2"]'::jsonb, 'Dev bên mình đang chạy 3 dự án cùng lúc, không ai nhớ hết các buổi họp đâu. File của bạn phải tự nói được mọi thứ.', 'Dự án đầu tiên của bạn ở agency xong rồi. Tuần sau có dự án mới, ngành khác hẳn. Quen dần đi nhé!', '[{"type": "character", "id": "frontend-developer"}, {"type": "term", "name": "Design System", "url": "https://academy.telos.vn/design-system-la-gi/"}]'::jsonb, true, null, '{"en": {"title": "Handoff and sign-off", "offer_text": "Our developers are running 3 projects at once, nobody remembers every meeting. Your file has to explain everything on its own.", "done_text": "Your first agency project is done. Next week there''s a new one, in a completely different industry. You''ll get used to it!"}}'::jsonb)
on conflict (id) do update set type = excluded.type, scale = excluded.scale, sort_order = excluded.sort_order, title = excluded.title, room_id = excluded.room_id, giver = excluded.giver, gather = excluded.gather, offer_text = excluded.offer_text, done_text = excluded.done_text, rewards = excluded.rewards, is_active = excluded.is_active, daily_date = excluded.daily_date, i18n = excluded.i18n;

-- 5. Bước nhiệm vụ
insert into tm_quest_steps (id, quest_id, sort_order, type, target, task_text, line_text, secs, i18n) values
  ('small-01-s1', 'small-01', 1, 'talk', 'tech-lead@P2', 'Hỏi Tech Lead phần nào của onboarding khó làm', 'Bước tải ảnh đại diện hơi nặng. Nếu bỏ được, team làm nhanh hơn 3 ngày.', null, '{"en": {"task_text": "Ask the Tech Lead which part of onboarding is hard to build", "line_text": "The profile photo upload step is a bit heavy. If we drop it, the team ships 3 days faster."}}'::jsonb),
  ('small-01-s2', 'small-01', 2, 'work', null, 'Về chỗ ngồi, vẽ wireframe onboarding', 'Wireframe gọn hơn nhiều khi bỏ bước ảnh đại diện. Gửi mình xem nhé!', 5, '{"en": {"task_text": "Go back to your desk and draw the onboarding wireframe", "line_text": "The wireframe is much leaner without the profile photo step. Send it over!"}}'::jsonb),
  ('small-02-s1', 'small-02', 1, 'talk', 'business-analyst@P3', 'Hỏi Business Analyst về yêu cầu kinh doanh', 'Người dùng thấy giá trị trong 3 phút đầu thì tỷ lệ nâng cấp cao gấp đôi. Onboarding phải dẫn tới đó.', null, '{"en": {"task_text": "Ask the Business Analyst about the business requirements", "line_text": "When users see value in the first 3 minutes, the upgrade rate doubles. Onboarding has to lead there."}}'::jsonb),
  ('small-03-s1', 'small-03', 1, 'talk', 'account-manager@P3', 'Hỏi Account Manager khách hàng than phiền gì', 'Khách doanh nghiệp muốn mời cả nhóm ngay khi đăng ký. Hiện phải làm sau, rất rối.', null, '{"en": {"task_text": "Ask the Account Manager what customers complain about", "line_text": "Business customers want to invite their whole team right at sign-up. Right now they have to do it later, and it''s confusing."}}'::jsonb),
  ('small-03-s2', 'small-03', 2, 'talk', 'user@P5', 'Ra Pantry hỏi trực tiếp một người dùng', 'Mình đăng ký xong mà không biết bấm vào đâu tiếp. Phải mò một lúc mới thấy.', null, '{"en": {"task_text": "Go to the Pantry and ask a user directly", "line_text": "I finished signing up and had no idea what to tap next. It took me a while to find it."}}'::jsonb),
  ('small-04-s1', 'small-04', 1, 'work', null, 'Về máy hoàn thiện file Figma và prototype', 'File xong rồi đó. Giờ bạn giải thích các trạng thái cho QA nhé.', 5, '{"en": {"task_text": "Go back to your computer and finish the Figma file and prototype", "line_text": "The file is done. Now walk QA through the states."}}'::jsonb),
  ('small-04-s2', 'small-04', 2, 'talk', 'qa-engineer@P2', 'Giải thích các trạng thái lỗi cho QA', 'Rõ rồi. Mình sẽ viết test case cho cả trạng thái mất mạng nữa.', null, '{"en": {"task_text": "Walk QA through the error states", "line_text": "Got it. I''ll write test cases for the offline state too."}}'::jsonb),
  ('small-05-s1', 'small-05', 1, 'present', null, 'Trình bày onboarding mới trên TV phòng họp', 'Cả phòng vỗ tay. CEO giơ tay muốn góp ý.', 6, '{"en": {"task_text": "Present the new onboarding on the meeting room TV", "line_text": "The whole room applauds. The CEO raises a hand to give feedback."}}'::jsonb),
  ('small-05-s2', 'small-05', 2, 'talk', 'ceo@P3', 'Hỏi ý kiến CEO', 'Rất rõ ràng. Mình thích việc người dùng thấy kết quả ngay ở bước 2. Ra mắt thôi!', null, '{"en": {"task_text": "Ask the CEO for feedback", "line_text": "Very clear. I like that users see a result right at step 2. Let''s ship it!"}}'::jsonb),
  ('large-01-s1', 'large-01', 1, 'talk', 'tech-lead@R03', 'Hỏi Tech Lead ước lượng effort', 'Khoảng 8 điểm. Nếu dùng lại component có sẵn trong Design System thì còn 5.', null, '{"en": {"task_text": "Ask the Tech Lead for an effort estimate", "line_text": "About 8 points. If we reuse existing Design System components, it''s 5."}}'::jsonb),
  ('large-01-s2', 'large-01', 2, 'work', null, 'Về chỗ ngồi, phác wireframe đầu tiên', 'Bản phác đầu tiên đã có. Story này vào sprint được rồi.', 5, '{"en": {"task_text": "Go back to your desk and sketch the first wireframe", "line_text": "The first sketch is ready. This story can go into the sprint."}}'::jsonb),
  ('large-02-s1', 'large-02', 1, 'talk', 'data-analyst@R07', 'Sang Data & Analytics xin số liệu funnel', 'Đây: 42% người dùng bỏ đi ở bước chọn sở thích. Đó là chỗ đáng sửa nhất.', null, '{"en": {"task_text": "Go to Data & Analytics for the funnel numbers", "line_text": "Here: 42% of users leave at the interest-picker step. That''s the place most worth fixing."}}'::jsonb),
  ('large-03-s1', 'large-03', 1, 'talk', 'ux-design-engineer@R05', 'Hỏi UX Design Engineer về component Chip', 'Chip có sẵn 3 trạng thái và đã có code. Bạn chỉ cần thêm trạng thái "đã chọn" có icon.', null, '{"en": {"task_text": "Ask the UX Design Engineer about the Chip component", "line_text": "Chip already has 3 states and the code exists. You only need to add a \"selected\" state with an icon."}}'::jsonb),
  ('large-04-s1', 'large-04', 1, 'present', null, 'Trình bày wireframe trên màn hình Critique', 'Mọi người đã xem xong. Giờ đi lấy góp ý từng người nhé.', 5, '{"en": {"task_text": "Present your wireframes on the Critique screen", "line_text": "Everyone has seen it. Now go get feedback from each person."}}'::jsonb),
  ('large-04-s2', 'large-04', 2, 'talk', 'product-designer@R02', 'Lấy góp ý từ Product Designer', 'Bước 2 có hai nút chính cạnh nhau, người dùng sẽ phân vân. Giữ một nút chính thôi.', null, '{"en": {"task_text": "Get feedback from the Product Designer", "line_text": "Step 2 has two primary buttons side by side, users will hesitate. Keep just one primary button."}}'::jsonb),
  ('large-04-s3', 'large-04', 3, 'talk', 'ux-designer@R04', 'Lấy góp ý từ UX Designer', 'Nên cho phép bỏ qua bước chọn sở thích. Đừng ép người dùng.', null, '{"en": {"task_text": "Get feedback from the UX Designer", "line_text": "Let people skip the interest-picker step. Don''t force users."}}'::jsonb),
  ('large-05-s1', 'large-05', 1, 'talk', 'user@R11', 'Nhờ User thử luồng onboarding và quan sát', 'Ủa, muốn bỏ qua bước này thì bấm ở đâu? À… cái chữ mờ mờ này hả. Mình tưởng nó bị khoá.', null, '{"en": {"task_text": "Ask the User to try the onboarding flow and observe", "line_text": "Hmm, where do I tap to skip this step? Oh… this faded text? I thought it was disabled."}}'::jsonb),
  ('large-05-s2', 'large-05', 2, 'talk', 'product-manager@R03', 'Chốt vấn đề vừa thấy với PM', 'Bạn thấy không? Người dùng không nhận ra nút "Bỏ qua" vì nó quá mờ.', null, '{"en": {"task_text": "Confirm the problem you just saw with the PM", "line_text": "See that? The user didn''t notice the \"Skip\" button because it''s too faint."}}'::jsonb),
  ('large-06-s1', 'large-06', 1, 'work', null, 'Về máy chuẩn bị spec và prototype', 'Spec có đủ trạng thái lỗi và trạng thái tải. Giải thích cho QA nhé.', 5, '{"en": {"task_text": "Go back to your computer and prepare the spec and prototype", "line_text": "The spec covers the error and loading states. Walk QA through it."}}'::jsonb),
  ('large-06-s2', 'large-06', 2, 'talk', 'qa-engineer@R03', 'Giải thích các trạng thái cho QA', 'Rõ rồi. Mình sẽ test thêm trường hợp mạng yếu và màn hình nhỏ.', null, '{"en": {"task_text": "Walk QA through the states", "line_text": "Got it. I''ll also test weak network and small screens."}}'::jsonb),
  ('large-07-s1', 'large-07', 1, 'present', null, 'Demo onboarding trên TV phòng họp', 'Demo rất mượt. Marketing và Customer Success đều có ý kiến.', 6, '{"en": {"task_text": "Demo the onboarding on the meeting room TV", "line_text": "A smooth demo. Marketing and Customer Success both have comments."}}'::jsonb),
  ('large-07-s2', 'large-07', 2, 'talk', 'growth-manager@R10', 'Nghe phản hồi từ Growth Manager', 'Mình muốn thêm bước mời bạn bè ngay cuối onboarding. Có làm được không?', null, '{"en": {"task_text": "Hear feedback from the Growth Manager", "line_text": "I''d like an invite-a-friend step right at the end of onboarding. Can we do that?"}}'::jsonb),
  ('large-07-s3', 'large-07', 3, 'talk', 'csm@R10', 'Nghe phản hồi từ Customer Success', 'Khách hàng sẽ rất thích. Họ hỏi chuyện này mỗi tuần.', null, '{"en": {"task_text": "Hear feedback from Customer Success", "line_text": "Customers will love it. They ask about this every week."}}'::jsonb),
  ('agency-01-s1', 'agency-01', 1, 'work', null, 'Về máy dựng nhanh mockup màn hình đặt lịch', 'Nhìn được đó! Có hình thật thì khách dễ hình dung hơn hẳn slide toàn chữ.', 5, '{"en": {"task_text": "Go back to your computer and quickly mock up the booking screen", "line_text": "That looks good! A real screen helps the client picture it far better than slides full of text."}}'::jsonb),
  ('agency-01-s2', 'agency-01', 2, 'talk', 'ceo@A6', 'Hỏi Founder nên nhấn điểm gì khi gặp khách', 'Đừng khoe nhiều tính năng. Cho họ thấy hội viên đặt được lịch trong 3 bước là đủ.', null, '{"en": {"task_text": "Ask the Founder what to emphasise with the client", "line_text": "Don''t show off lots of features. Showing members can book a class in 3 steps is enough."}}'::jsonb),
  ('agency-02-s1', 'agency-02', 1, 'talk', 'client@A4', 'Hỏi Client mục tiêu của dự án', 'Bên anh có 12 phòng tập. Hội viên toàn gọi điện đặt lịch nên lễ tân quá tải. Anh muốn sau 3 tháng, 70% lượt đặt lịch đi qua app.', null, '{"en": {"task_text": "Ask the Client about the project goals", "line_text": "We have 12 gyms. Members all phone in to book, so reception is overloaded. In 3 months I want 70% of bookings to go through the app."}}'::jsonb),
  ('agency-02-s2', 'agency-02', 2, 'talk', 'project-manager@A3', 'Chốt lại ghi chú với Project Manager', 'Mình ghi nhận: mục tiêu là giảm cuộc gọi đặt lịch. Mọi màn hình sau này phải phục vụ điều đó.', null, '{"en": {"task_text": "Go over your notes with the Project Manager", "line_text": "Noted: the goal is fewer booking calls. Every screen from now on has to serve that."}}'::jsonb),
  ('agency-03-s1', 'agency-03', 1, 'talk', 'business-analyst@A3', 'Hỏi Business Analyst danh sách màn hình', 'Khách liệt kê 24 màn hình. Nhưng để hội viên đặt được lịch thì chỉ cần 9 màn hình là chạy được.', null, '{"en": {"task_text": "Ask the Business Analyst for the list of screens", "line_text": "The client listed 24 screens. But for members to book a class, 9 screens are enough to get it running."}}'::jsonb),
  ('agency-03-s2', 'agency-03', 2, 'talk', 'tech-lead@A2', 'Sang Dev team hỏi Tech Lead cái nào làm kịp', '9 màn hình thì kịp 8 tuần. Riêng thanh toán online nên để giai đoạn 2, tích hợp cổng thanh toán mất ít nhất 3 tuần.', null, '{"en": {"task_text": "Go to the Dev team and ask the Tech Lead what fits in time", "line_text": "9 screens fit in 8 weeks. Online payments should wait for phase 2, integrating a payment gateway takes at least 3 weeks."}}'::jsonb),
  ('agency-04-s1', 'agency-04', 1, 'work', null, 'Về máy làm concept luồng đặt lịch', 'Xong concept rồi à? Trước khi mình xem, bạn hỏi Graphic Designer về nhận diện của khách đã.', 5, '{"en": {"task_text": "Go back to your computer and make a concept for the booking flow", "line_text": "Concept done? Before I look, ask the Graphic Designer about the client''s brand identity."}}'::jsonb),
  ('agency-04-s2', 'agency-04', 2, 'talk', 'graphic-designer@A1', 'Hỏi Graphic Designer về màu thương hiệu của khách', 'Logo khách màu cam đậm. Bạn chỉ dùng cam cho nút chính thôi, đừng phủ cả màn hình, chói lắm.', null, '{"en": {"task_text": "Ask the Graphic Designer about the client''s brand colours", "line_text": "The client''s logo is a deep orange. Use orange only for the primary button, don''t cover the whole screen, it''s too loud."}}'::jsonb),
  ('agency-05-s1', 'agency-05', 1, 'present', null, 'Trình bày concept trên TV phòng họp', 'Bạn vừa trình bày xong. Khách gật gù, nhưng có vẻ còn muốn nói gì đó.', 6, '{"en": {"task_text": "Present the concept on the meeting room TV", "line_text": "You''ve just finished presenting. The client nods, but seems to want to say something."}}'::jsonb),
  ('agency-05-s2', 'agency-05', 2, 'talk', 'client@A4', 'Nghe phản hồi của Client', 'Luồng đặt lịch thì anh thích. Nhưng trang chủ trống quá. Em thêm banner khuyến mãi, tin tức, rồi bảng xếp hạng hội viên nữa nhé.', null, '{"en": {"task_text": "Hear the Client''s feedback", "line_text": "I like the booking flow. But the home screen is too empty. Add promo banners, news, and a member leaderboard too."}}'::jsonb),
  ('agency-06-s1', 'agency-06', 1, 'talk', 'project-manager@A3', 'Đừng nhận lời vội. Về hỏi Project Manager', 'Hai phần đó nằm ngoài hợp đồng, cộng lại khoảng 4 tuần nữa. Mình sẽ báo giá bổ sung. Khách đồng ý thì mới làm.', null, '{"en": {"task_text": "Don''t say yes yet. Go ask the Project Manager", "line_text": "Those two parts are outside the contract, about 4 more weeks combined. I''ll send an additional quote. We only build it if the client agrees."}}'::jsonb),
  ('agency-06-s2', 'agency-06', 2, 'talk', 'account-manager@A3', 'Nhờ Account Manager nói lại với khách', 'Để mình nói. Bạn cứ giữ thái độ vui vẻ: đừng từ chối thẳng, mà cũng đừng hứa.', null, '{"en": {"task_text": "Ask the Account Manager to talk to the client", "line_text": "Let me handle it. Just stay friendly: don''t refuse outright, but don''t promise either."}}'::jsonb),
  ('agency-07-s1', 'agency-07', 1, 'talk', 'user@A5', 'Ra Pantry nhờ User dùng thử trang chủ', 'Mình mở app là muốn đặt lịch ngay. Mấy cái banner này che mất nút, mình tưởng quảng cáo nên lướt qua luôn.', null, '{"en": {"task_text": "Go to the Pantry and ask the User to try the home screen", "line_text": "When I open the app I want to book right away. These banners hide the button, I thought they were ads so I just scrolled past."}}'::jsonb),
  ('agency-07-s2', 'agency-07', 2, 'talk', 'client@A4', 'Mang kết quả cho Client xem', 'Hội viên nói vậy thật à? Thôi được, banner cho xuống dưới, nút đặt lịch để trên cùng.', null, '{"en": {"task_text": "Show the results to the Client", "line_text": "A member really said that? Fine, move the banners down and put the booking button at the top."}}'::jsonb),
  ('agency-08-s1', 'agency-08', 1, 'work', null, 'Về máy chuẩn bị spec và prototype', 'Spec đủ các trạng thái rồi. Giờ bạn giải thích cho Frontend nhé.', 5, '{"en": {"task_text": "Go back to your computer and prepare the spec and prototype", "line_text": "The spec covers all the states. Now walk the Frontend developer through it."}}'::jsonb),
  ('agency-08-s2', 'agency-08', 2, 'talk', 'frontend-developer@A2', 'Giải thích spec cho Frontend Developer', 'Rõ rồi. Mình dùng lại bộ component của dự án trước, chỉ đổi màu theo thương hiệu khách.', null, '{"en": {"task_text": "Walk the Frontend Developer through the spec", "line_text": "Got it. I''ll reuse the component set from the last project and just swap in the client''s brand colours."}}'::jsonb),
  ('agency-08-s3', 'agency-08', 3, 'talk', 'client@A4', 'Mời Client nghiệm thu sản phẩm', 'App chạy đúng như bản thiết kế. Anh ký nghiệm thu. Giai đoạn 2 anh làm tiếp với bên em.', null, '{"en": {"task_text": "Invite the Client to sign off the product", "line_text": "The app works exactly like the design. I''m signing off. We''ll do phase 2 with your team too."}}'::jsonb)
on conflict (id) do update set quest_id = excluded.quest_id, sort_order = excluded.sort_order, type = excluded.type, target = excluded.target, task_text = excluded.task_text, line_text = excluded.line_text, secs = excluded.secs, i18n = excluded.i18n;

-- 6. Gắn nhân vật với thuật ngữ nhóm "Vai trò": theo URL bài viết (bỏ dấu / cuối khi so sánh),
--    hoặc theo tên thuật ngữ gợi ý (term_search). Khớp → đặt term_id và xoá article_url (game lấy URL của thuật ngữ).
--    Không khớp → giữ article_url.
with recursive vt as (
  select id from categories where slug = 'vai-tro'
  union all
  select c.id from categories c join vt on c.parent_id = vt.id
), hint(cid, name) as (values ('graphic-designer', 'Graphic Designer'), ('freelancer', 'Freelancer')
), m as (
  select distinct on (ch.id) ch.id as cid, t.id as tid
  from tm_characters ch
  left join hint h on h.cid = ch.id
  join concepts t on t.category_id in (select id from vt)
                 and ((t.url is not null and ch.article_url is not null and rtrim(lower(t.url), '/') = rtrim(lower(ch.article_url), '/'))
                      or (h.name is not null and lower(t.name) = lower(h.name)))
  where true and ch.term_id is null
  order by ch.id, t.is_published desc
)
update tm_characters ch set term_id = m.tid, article_url = null from m where ch.id = m.cid;

-- 7. Thẻ thưởng: {type:'term', name, url} → {type:'term', term_id}.
--    Ưu tiên khớp cả tên lẫn URL (vd Agile và Waterfall dùng chung một bài), rồi theo tên, rồi theo URL.
--    Không khớp thì giữ nguyên dạng cũ (game vẫn hiện tên + link) và liệt kê ở báo cáo bên dưới.
update tm_quests q set rewards = (
  select coalesce(jsonb_agg(
    case when r ->> 'type' = 'term' and not (r ? 'term_id') then coalesce(
      (select jsonb_build_object('type', 'term', 'term_id', t.id) from concepts t
        where lower(t.name) = lower(r ->> 'name')
        order by (t.url is not null and rtrim(lower(t.url), '/') = rtrim(lower(r ->> 'url'), '/')) desc, t.is_published desc limit 1),
      (select jsonb_build_object('type', 'term', 'term_id', t.id) from concepts t
        where t.url is not null and rtrim(lower(t.url), '/') = rtrim(lower(r ->> 'url'), '/')
        order by t.is_published desc limit 1),
      r)
    else r end order by n), '[]'::jsonb)
  from jsonb_array_elements(q.rewards) with ordinality as e(r, n)
) where true;

commit;

-- 8. BÁO CÁO — nhân vật nào đã gắn thuật ngữ, thẻ thưởng nào chưa khớp thuật ngữ (cần xử lý tay trong CMS)
select 'Nhân vật đã gắn thuật ngữ' as loai, ch.id as ma, ch.title || ' → ' || t.name as chi_tiet
from tm_characters ch join concepts t on t.id = ch.term_id where true
union all
select 'Nhân vật có link riêng, chưa gắn thuật ngữ', ch.id, ch.article_url
from tm_characters ch where true and ch.term_id is null and ch.article_url is not null
union all
select 'Nhân vật chưa có bài', ch.id, ch.title
from tm_characters ch where true and ch.term_id is null and ch.article_url is null and ch.kind = 'role'
union all
select 'Thẻ thưởng CHƯA khớp thuật ngữ', q.id, (r ->> 'name') || ' · ' || coalesce(r ->> 'url', '')
from tm_quests q, jsonb_array_elements(q.rewards) r
where true and r ->> 'type' = 'term' and not (r ? 'term_id')
order by 1, 2;
