-- ════════════════════════════════════════════════════════
-- TEAM MAP — bản tiếng Anh (sinh tự động bởi scripts/gen_team_map_seed.py, đừng sửa tay)
-- Chạy sau supabase_team_map.sql. Chỉ ghi cột i18n.en (nội dung trang /en/team-map),
-- không đụng tới nội dung tiếng Việt. Chạy lại sẽ ghi đè bản tiếng Anh đã sửa trong CMS.
-- ════════════════════════════════════════════════════════
begin;

-- tm_characters: 54 dòng
update tm_characters t set i18n = jsonb_set(t.i18n, '{en}', v.en) from (values
  ('ceo', '{"summary": "The person ultimately responsible for the company''s vision and business results.", "doing": "Reviewing this quarter''s OKRs with the leadership team.", "with_designer": "Rarely works with designers directly, but the company goals the CEO sets decide what you design for."}'::jsonb),
  ('cpo', '{"summary": "Owns product strategy and manages the team of Product Managers.", "doing": "Finalising the roadmap for the next two quarters.", "with_designer": "Approves big product directions. You will present to the CPO at strategy reviews."}'::jsonb),
  ('cto', '{"summary": "Owns technology, system architecture and the engineering team.", "doing": "Reviewing this month''s infrastructure costs.", "with_designer": "Sets the technical constraints, which shape what designers can propose."}'::jsonb),
  ('head-of-design', '{"summary": "Leads the whole Design chapter: hiring, design quality and career paths for designers.", "doing": "Building a competency framework for every designer level.", "with_designer": "Your most senior craft manager (solid line). You meet at Design all-hands."}'::jsonb),
  ('head-of-data', '{"summary": "Leads the Data & Analytics team and standardises how the company measures things.", "doing": "Standardising the North Star metrics.", "with_designer": "Provides the numbers that tell you whether a design actually works."}'::jsonb),
  ('head-of-eng', '{"summary": "Manages the Engineering Managers, the QA Lead and overall engineering quality.", "doing": "Staffing a new squad.", "with_designer": "Rarely works with you directly, but decides how fast developers move and how they work with you."}'::jsonb),
  ('product-manager', '{"summary": "Owns the direction and outcomes of the product: what to build, why, and in what order.", "doing": "Writing user stories for the onboarding flow.", "with_designer": "Sets your priorities every sprint (dotted line). The person you talk to most every day."}'::jsonb),
  ('product-owner', '{"summary": "The Scrum role that manages the product backlog and decides the priorities for each sprint.", "doing": "Ordering the backlog for next sprint.", "with_designer": "Clarifies the acceptance criteria for each of your designs."}'::jsonb),
  ('growth-pm', '{"summary": "A PM focused on growth metrics: activation, retention, referral.", "doing": "Reading the A/B test results for the sign-up screen.", "with_designer": "Designs experiments with you and reads the A/B test results together."}'::jsonb),
  ('data-pm', '{"summary": "A PM for internal data products such as dashboards and tracking systems.", "doing": "Defining event tracking for a new feature.", "with_designer": "Helps you set up the right tracking to measure how well a design performs."}'::jsonb),
  ('ui-ux-designer', '{"summary": "Designs interfaces and user experiences, combining UX thinking with UI skills.", "doing": "This is you. You are designing a new onboarding flow.", "with_designer": "Sits in the squad, gets priorities from the PM, reports on craft to the Design Manager."}'::jsonb),
  ('product-designer', '{"summary": "An end-to-end design role, from research and UX to UI, tied closely to product goals.", "doing": "Drawing the user flow for the invite-a-friend feature.", "with_designer": "A colleague in the same chapter. You two often meet at Design Critique."}'::jsonb),
  ('ui-designer', '{"summary": "Focuses on the interface: layout, colour, type and components.", "doing": "Polishing the profile screen to match the Design System.", "with_designer": "Same chapter. Often talks with you about using components the right way."}'::jsonb),
  ('ux-designer', '{"summary": "Focuses on the experience: flows, information architecture and interaction.", "doing": "Redrawing the checkout flow down to 3 steps.", "with_designer": "Same chapter. Often reviews user flows with you before moving to UI."}'::jsonb),
  ('intern', '{"summary": "A UI/UX intern who learns by working alongside a lead designer.", "doing": "Practising wireframes with your guidance.", "with_designer": "You are their direct mentor. The intern asks you everything, from Figma files to how meetings work."}'::jsonb),
  ('ds-designer', '{"summary": "Builds and maintains the Design System: the component library, tokens and guidelines for the whole product.", "doing": "Adding new variants to the Button component.", "with_designer": "Ask them before drawing a new component. It may already exist."}'::jsonb),
  ('ux-design-engineer', '{"summary": "Combines UX thinking, design and code to ship high-quality experiences themselves.", "doing": "Moving colour tokens from Figma into CSS.", "with_designer": "The bridge between your Figma file and real code."}'::jsonb),
  ('design-manager', '{"summary": "Directly manages designers: quality reviews, 1-on-1s, career growth.", "doing": "Preparing this afternoon''s Design Critique.", "with_designer": "Your direct craft manager (solid line). You have a 1-on-1 every two weeks."}'::jsonb),
  ('ux-researcher', '{"summary": "Plans and runs user research.", "doing": "Writing the script for a Usability Test.", "with_designer": "Helps you validate designs with real users before anything gets built."}'::jsonb),
  ('ux-writer', '{"summary": "Writes the words in the interface: buttons, messages, instructions, error states.", "doing": "Rewriting the login error messages.", "with_designer": "Polishes the copy on every screen with you."}'::jsonb),
  ('motion-designer', '{"summary": "Creates motion and animation in the product, from micro-interactions to transitions.", "doing": "Animating the onboarding transitions.", "with_designer": "Turns the interactions you design into smooth motion."}'::jsonb),
  ('tech-lead', '{"summary": "The engineer who leads technical work in the squad and owns the solution and code quality.", "doing": "Estimating effort for a new story.", "with_designer": "Forms the product trio with you and the PM. Answers the questions: can we build it, and how long will it take?"}'::jsonb),
  ('frontend-developer', '{"summary": "The developer who builds the user interface, turning your Figma file into a product that runs in the browser.", "doing": "Building the Card component from your Figma file.", "with_designer": "Receives your handoff. Will ask about spacing, states and responsive behaviour."}'::jsonb),
  ('backend-developer', '{"summary": "The developer behind server-side logic, data and APIs.", "doing": "Writing the API that saves onboarding progress.", "with_designer": "Tells you what data is available and how fast the system can respond."}'::jsonb),
  ('fullstack-developer', '{"summary": "A developer who works on both frontend and backend, flexible for teams that need speed.", "doing": "Building an SEO landing page end to end.", "with_designer": "Often tries out an idea with you in just a few days."}'::jsonb),
  ('mobile-developer', '{"summary": "A developer building iOS and Android apps.", "doing": "Fixing a swipe gesture bug on Android.", "with_designer": "Asks you about pattern differences between iOS and Android."}'::jsonb),
  ('qa-engineer', '{"summary": "A test engineer who makes sure the product works correctly before release.", "doing": "Writing test cases for the checkout flow.", "with_designer": "Compares the build against your design and flags anything that does not match."}'::jsonb),
  ('software-architect', '{"summary": "Designs the overall architecture of the system.", "doing": "Diagramming how to split out the payment service.", "with_designer": "Rarely works with you directly, but their decisions affect speed and feature limits."}'::jsonb),
  ('devops', '{"summary": "Builds the infrastructure and deploy pipelines, and keeps the system running.", "doing": "Watching this afternoon''s deploy.", "with_designer": "When the product is slow or goes down, they are the first to respond."}'::jsonb),
  ('data-analyst', '{"summary": "Analyses data to answer questions about the product and the business.", "doing": "Building this week''s sign-up funnel.", "with_designer": "Shows you at which step of a flow users drop off."}'::jsonb),
  ('bi-analyst', '{"summary": "Builds dashboards and recurring reports for every department.", "doing": "Updating the revenue dashboard.", "with_designer": "Their dashboards are the fastest place to find numbers."}'::jsonb),
  ('data-scientist', '{"summary": "Builds prediction and recommendation models from data.", "doing": "Training the course recommendation model.", "with_designer": "Designs with you how AI-generated recommendations are shown."}'::jsonb),
  ('data-engineer', '{"summary": "Builds the data pipelines that let other teams use data.", "doing": "Fixing last night''s data sync pipeline.", "with_designer": "Rarely works with you directly, but the tracking you propose needs them to run."}'::jsonb),
  ('scrum-master', '{"summary": "Keeps the Scrum rhythm: runs the ceremonies and clears blockers for the team.", "doing": "Preparing the end-of-sprint Retro.", "with_designer": "Helps you unblock work that is stuck in the sprint."}'::jsonb),
  ('delivery-manager', '{"summary": "Makes sure teams ship on time and coordinate well with each other.", "doing": "Updating the release plan.", "with_designer": "Tells you the real deadline for a feature."}'::jsonb),
  ('project-manager', '{"summary": "Manages projects by scope, time and resources.", "doing": "Tracking progress on the partner integration project.", "with_designer": "Needs you to estimate design time for each work item."}'::jsonb),
  ('growth-manager', '{"summary": "Drives user growth across many marketing channels.", "doing": "Planning a refer-a-friend campaign.", "with_designer": "Needs you to design landing pages and the invite-a-friend flow."}'::jsonb),
  ('performance-marketer', '{"summary": "Runs paid ads and optimises the cost per user.", "doing": "Comparing 3 ad banner variants.", "with_designer": "Often asks you for banner variants and landing pages."}'::jsonb),
  ('brand-manager', '{"summary": "Protects the brand''s image and voice.", "doing": "Approving the identity kit for a new campaign.", "with_designer": "You need to follow the brand guidelines they set."}'::jsonb),
  ('content-marketer', '{"summary": "Writes content for the blog, social media and email.", "doing": "Writing the launch blog post for a feature.", "with_designer": "Needs feature illustrations from you."}'::jsonb),
  ('crm-manager', '{"summary": "Manages email, notifications and customer retention programmes.", "doing": "Setting up the welcome email sequence.", "with_designer": "Designs emails and in-app messages with you."}'::jsonb),
  ('seo-specialist', '{"summary": "Optimises the website to rank well on Google.", "doing": "Checking page load speed.", "with_designer": "Gives feedback on page structure and headings when you build landing pages."}'::jsonb),
  ('csm', '{"summary": "Helps customers succeed with the product and renew.", "doing": "Calling customers whose plans are about to expire.", "with_designer": "Brings real customer feedback back to you."}'::jsonb),
  ('customer-support', '{"summary": "Answers customer questions and handles their problems.", "doing": "Answering 12 tickets about forgotten passwords.", "with_designer": "A valuable source of insight: which problems users ask about most."}'::jsonb),
  ('account-manager', '{"summary": "Manages relationships and contracts with large customers.", "doing": "Preparing a demo for an enterprise customer.", "with_designer": "Needs you to make a polished demo for big customers."}'::jsonb),
  ('business-analyst', '{"summary": "Analyses business requirements and translates them into specifications for design and engineering.", "doing": "Writing the requirements spec for the invoicing feature.", "with_designer": "Translates business requirements into specs for you to design from."}'::jsonb),
  ('stakeholder', '{"summary": "People with a stake in the product, who can influence or be affected by design decisions.", "doing": "Waiting for the Sprint Review to see the demo.", "with_designer": "You need to convince them with reasons, data and a clear demo."}'::jsonb),
  ('nhan-luu', '{"summary": "This guy is the Academic Director at TELOS Academy and the author of this game. He wanders from room to room telling unfunny jokes that lower everyone''s productivity.", "doing": "Walking around the office, checking in on every team.", "with_designer": "He can show you a learning path for UI/UX and where to grow in this field.", "tag": "Academic Director · TELOS Academy", "cta": ["Get a gift", "Learn more"]}'::jsonb),
  ('user', '{"summary": "A real user of the product. They don''t care how the team works, only whether the product is easy to use.", "doing": "Tapping away on their phone, trying out the app.", "with_designer": "Asking and watching real users is the fastest way to know whether your design actually works.", "tag": "Real user", "cta": ["Usability Testing", "Learnability"]}'::jsonb),
  ('client', '{"summary": "The customer who hires the agency to build their product. They pay, set the goals and have the final say, but they are not the product''s users.", "doing": "Waiting for the meeting while answering work messages.", "with_designer": "You present designs to them and listen to their feedback. Every new request from them must go through the Account Manager and the Project Manager.", "tag": "The agency''s client"}'::jsonb),
  ('design-director', '{"summary": "Responsible for the design quality of the whole agency. Every design has to pass the Design Director before it goes to a client.", "doing": "Reviewing concepts for three different projects.", "with_designer": "Your direct craft manager. Approves designs, gives feedback and decides which version is good enough to send to the client."}'::jsonb),
  ('graphic-designer', '{"summary": "A designer who works on brand identity, banners, illustrations and marketing materials.", "doing": "Adjusting the banner set for a client''s grand opening campaign.", "with_designer": "Tells you the client''s brand colours, fonts and imagery so the interface stays on brand."}'::jsonb),
  ('sales', '{"summary": "Finds clients and brings projects into the agency.", "doing": "Preparing slides for this afternoon''s client meeting.", "with_designer": "Often asks you to put together a quick demo so the client can picture the product before signing."}'::jsonb),
  ('freelancer', '{"summary": "An independent designer the agency hires per project when the team is short on people.", "doing": "Making an icon set for a project that is due this week.", "with_designer": "Works with you for a few weeks and then leaves. Hand over clean files so they can get going fast."}'::jsonb)
) as v(id, en) where t.id = v.id;

-- tm_rooms: 23 dòng
update tm_rooms t set i18n = jsonb_set(t.i18n, '{en}', v.en) from (values
  ('P1', '{"code": "Team 1", "name": "Product team", "intro": "This is your spot. The Product Manager decides what to build and in what order, you design, and the Intern learns alongside you. In a small company, designers often handle research and interface copy too."}'::jsonb),
  ('P2', '{"code": "Team 2", "name": "Dev team", "intro": "The Tech Lead, Frontend, Backend, Mobile and QA turn designs into a working product. You come here to hand off, answer questions and review builds."}'::jsonb),
  ('P3', '{"code": "Team 3", "name": "Business team", "intro": "The CEO, Marketing, Sales, Customer Support and the Business Analyst. This is where business goals are set and the customer''s voice is heard, a valuable source of insight for design."}'::jsonb),
  ('P4', '{"code": "Meeting", "name": "Meeting room", "intro": "Used for Sprint Planning, end-of-sprint demos and company-wide meetings. The TV is for presenting designs."}'::jsonb),
  ('P5', '{"code": "Shared", "name": "Pantry", "intro": "A shared space for breaks, chance encounters and guild meetups. Many good ideas start with a chat here."}'::jsonb),
  ('P6', '{"code": "Closed", "name": "Other departments"}'::jsonb),
  ('R01', '{"code": "R01", "name": "Leadership", "intro": "The CEO, CPO, CTO and the Heads. They set strategy and OKRs for the whole company. The Head of Design is your most senior craft manager."}'::jsonb),
  ('R07', '{"code": "R07", "name": "Data & Analytics", "intro": "Data Analyst, BI Analyst, Data Scientist and Data Engineer. Drop by when you need funnel numbers or A/B test results."}'::jsonb),
  ('R08', '{"code": "R08", "name": "Meeting room", "intro": "Sprint Planning and Sprint Review happen here. Stakeholders often come to the demo."}'::jsonb),
  ('R02', '{"code": "R02", "name": "Tribe Growth", "intro": "The squads behind onboarding, activation and referrals. Designers here work a lot with A/B tests and growth metrics."}'::jsonb),
  ('R03', '{"code": "R03", "name": "Core Experience", "intro": "Your squad: the PM, designers, Tech Lead, developers and QA share one table. This is where you work every day."}'::jsonb),
  ('R04', '{"code": "R04", "name": "Monetization", "intro": "The squad behind payments and plans. Designers here work closely with pricing and legal constraints."}'::jsonb),
  ('R05', '{"code": "R05", "name": "Platform", "intro": "DevOps, the Software Architect and the Design System team. Ask the Design System team before drawing a new component."}'::jsonb),
  ('R06', '{"code": "R06", "name": "Design Studio", "intro": "The craft home for designers: Design Manager, UX Researcher, UX Writer, Motion Designer. Design Critique happens here every week."}'::jsonb),
  ('R09', '{"code": "R09", "name": "Delivery Hub", "intro": "The Scrum Master, Delivery Manager and Project Manager keep the sprint rhythm and the release deadlines."}'::jsonb),
  ('R11', '{"code": "Shared", "name": "Pantry", "intro": "A shared space for breaks, chance encounters and guild meetups. Users invited for interviews often wait here too."}'::jsonb),
  ('R10', '{"code": "R10", "name": "Neighbours · behind the glass", "intro": "Marketing, Customer Success, Sales and the Business Analyst sit behind the glass wall. They are the stakeholders you work with most often."}'::jsonb),
  ('A1', '{"code": "Team 1", "name": "Design team", "intro": "At an agency you work on several projects at once, each in a different industry. You learn fast and wide, but rarely stay on one product long enough to see the results. Your designs are approved by the Design Director."}'::jsonb),
  ('A2', '{"code": "Team 2", "name": "Dev team", "intro": "A developer here may run 2–3 projects at once and usually skips client meetings. Your design files have to explain everything on their own."}'::jsonb),
  ('A3', '{"code": "Team 3", "name": "Account & Project", "intro": "Every client request goes through here. The Account Manager owns the relationship, the Project Manager owns scope, schedule and budget. Never promise the client anything before checking with the Project Manager."}'::jsonb),
  ('A4', '{"code": "Meeting", "name": "Client meeting room", "intro": "Where concepts are presented and client feedback is heard. A good design that is presented badly still gets rejected: at an agency, presenting matters as much as designing."}'::jsonb),
  ('A5', '{"code": "Shared", "name": "Pantry", "intro": "A shared space for breaks and meetups. Users invited to try the client''s product wait here too."}'::jsonb),
  ('A6', '{"code": "Team 4", "name": "Sales", "intro": "Where projects come into the company. Designers are often asked to put together a quick demo so Sales can convince clients to sign."}'::jsonb)
) as v(id, en) where t.id = v.id;

-- tm_quests: 21 dòng
update tm_quests t set i18n = jsonb_set(t.i18n, '{en}', v.en) from (values
  ('small-01', '{"title": "Picking up work at sprint start", "offer_text": "Hi! This sprint we''re redoing the onboarding flow. Before you start drawing, ask the Tech Lead which parts are hard to build.", "done_text": "Great, the wireframe is clear. We''ll leave the profile photo step for next sprint."}'::jsonb),
  ('small-02', '{"title": "Understanding the business goal", "offer_text": "This quarter the company needs 20% more paying users. Ask the BA how onboarding ties into that.", "done_text": "Exactly. A design that helps users see value early is a good design."}'::jsonb),
  ('small-03', '{"title": "Listening to customers", "offer_text": "We get a lot of questions about the sign-up step. Go ask the Account Manager for the big customers'' point of view too.", "done_text": "Add these two insights to the persona. Thanks for listening!"}'::jsonb),
  ('small-04', '{"title": "Handoff to the Dev team", "offer_text": "Is the Figma file done? Before we code, please walk QA through the error states.", "done_text": "Thank you. With a clickable prototype I understood the flow much faster."}'::jsonb),
  ('small-05', '{"title": "End-of-sprint demo", "offer_text": "Demo time! The whole company is in the meeting room. Present your work, then ask the CEO for feedback.", "done_text": "Your first sprint is done. Welcome to the team!"}'::jsonb),
  ('large-01', '{"title": "Sprint Planning", "offer_text": "This sprint the Core squad is redoing the onboarding flow. Ask the Tech Lead to estimate the effort for the new design.", "done_text": "OK, I''m putting this story into the sprint. Remember to drop by the Design System team."}'::jsonb),
  ('large-02', '{"title": "Discovery with data", "offer_text": "Before drawing, we need to know where users drop off. Go to Data & Analytics and ask for the funnel numbers.", "done_text": "42% is a big number. The problem is clear now, only then do we move to solutions."}'::jsonb),
  ('large-03', '{"title": "Checking the components", "offer_text": "Planning to draw a new interest-picker card? Ask the UX Design Engineer what the Chip component already has.", "done_text": "So we add a variant instead of a new component. Thanks for asking first!"}'::jsonb),
  ('large-04', '{"title": "Design Critique", "offer_text": "This afternoon it''s your turn to present your wireframes. Get feedback from the Product Designer and the UX Designer.", "done_text": "Two great pieces of feedback. Critique is there to make the design better, not to grade you."}'::jsonb),
  ('large-05', '{"title": "Usability Test", "offer_text": "I''ve invited a real user, they''re sitting in the Pantry. Let''s ask them to try the onboarding flow together.", "done_text": "A real problem, from a real user. Fix that button''s contrast before handoff."}'::jsonb),
  ('large-06', '{"title": "Handoff", "offer_text": "Is the file ready? Please walk QA through the error and loading states.", "done_text": "With a clickable prototype the whole team got the flow really fast. Thank you!"}'::jsonb),
  ('large-07', '{"title": "Sprint Review", "offer_text": "Demo time. Marketing and Customer Success are both here. Listen to feedback from both sides.", "done_text": "I''ll put both ideas into next sprint''s backlog. Your demo was very convincing."}'::jsonb),
  ('large-08', '{"title": "End-of-sprint 1-on-1", "offer_text": "This sprint you worked with almost every department. Let''s talk about your growth goals.", "done_text": "Goals for next quarter: run a Critique session yourself and start a portfolio piece from this project."}'::jsonb),
  ('agency-01', '{"title": "A demo to close the deal", "offer_text": "This afternoon I''m meeting a gym chain that wants a class-booking app. Can you put together one demo screen for me? It doesn''t need to be complete, just enough for the client to picture it.", "done_text": "We closed it! The client signed an 8-week contract. Kickoff is next week and you''re on this project."}'::jsonb),
  ('agency-02', '{"title": "Kickoff and the brief", "offer_text": "Kickoff with the client is today. Don''t jump into the interface yet. Ask what they want to achieve and who their members are.", "done_text": "Great questions. Now that we know the client''s goal, we have grounds to say no to off-topic requests later."}'::jsonb),
  ('agency-03', '{"title": "Locking the project scope", "offer_text": "The contract is 8 weeks with a fixed budget. Ask the BA for the list of screens, then ask the Tech Lead whether we can make it in time.", "done_text": "So phase 1 is 9 screens, no payments yet. I''ll write it into the minutes so nobody argues about it later."}'::jsonb),
  ('agency-04', '{"title": "Internal review", "offer_text": "Before anything goes to the client, it goes through me. Make a concept for the booking flow and bring it here.", "done_text": "A clear 3-step flow. Fix the text contrast on the orange background and it can go to the client. Remember: clients should only see work that passed internal review."}'::jsonb),
  ('agency-05', '{"title": "Presenting to the client", "offer_text": "The client is here. Present your concept. Remember to start from their goals, not from the colours.", "done_text": "The client likes the main flow, that''s a big win. Don''t say yes right away to the extras they asked for, let me and the PM check the contract first."}'::jsonb),
  ('agency-06', '{"title": "The client changes their mind", "offer_text": "Oh, while you''re at it, can you also add online class packages and a points-for-rewards scheme? Should only be a few more screens.", "done_text": "OK, I get it. Let''s finish phase 1 first, and your team can send me a quote for the rest later."}'::jsonb),
  ('agency-07', '{"title": "Winning the argument with users", "offer_text": "The client still wants to stuff banners onto the home screen. If we argue with personal opinions, we lose. Go to the Pantry, have a member try it, and bring back the results.", "done_text": "See? The client doesn''t listen to designers, but they do listen to their users. Next time, test before you argue."}'::jsonb),
  ('agency-08', '{"title": "Handoff and sign-off", "offer_text": "Our developers are running 3 projects at once, nobody remembers every meeting. Your file has to explain everything on its own.", "done_text": "Your first agency project is done. Next week there''s a new one, in a completely different industry. You''ll get used to it!"}'::jsonb)
) as v(id, en) where t.id = v.id;

-- tm_quest_steps: 40 dòng
update tm_quest_steps t set i18n = jsonb_set(t.i18n, '{en}', v.en) from (values
  ('small-01-s1', '{"task_text": "Ask the Tech Lead which part of onboarding is hard to build", "line_text": "The profile photo upload step is a bit heavy. If we drop it, the team ships 3 days faster."}'::jsonb),
  ('small-01-s2', '{"task_text": "Go back to your desk and draw the onboarding wireframe", "line_text": "The wireframe is much leaner without the profile photo step. Send it over!"}'::jsonb),
  ('small-02-s1', '{"task_text": "Ask the Business Analyst about the business requirements", "line_text": "When users see value in the first 3 minutes, the upgrade rate doubles. Onboarding has to lead there."}'::jsonb),
  ('small-03-s1', '{"task_text": "Ask the Account Manager what customers complain about", "line_text": "Business customers want to invite their whole team right at sign-up. Right now they have to do it later, and it''s confusing."}'::jsonb),
  ('small-03-s2', '{"task_text": "Go to the Pantry and ask a user directly", "line_text": "I finished signing up and had no idea what to tap next. It took me a while to find it."}'::jsonb),
  ('small-04-s1', '{"task_text": "Go back to your computer and finish the Figma file and prototype", "line_text": "The file is done. Now walk QA through the states."}'::jsonb),
  ('small-04-s2', '{"task_text": "Walk QA through the error states", "line_text": "Got it. I''ll write test cases for the offline state too."}'::jsonb),
  ('small-05-s1', '{"task_text": "Present the new onboarding on the meeting room TV", "line_text": "The whole room applauds. The CEO raises a hand to give feedback."}'::jsonb),
  ('small-05-s2', '{"task_text": "Ask the CEO for feedback", "line_text": "Very clear. I like that users see a result right at step 2. Let''s ship it!"}'::jsonb),
  ('large-01-s1', '{"task_text": "Ask the Tech Lead for an effort estimate", "line_text": "About 8 points. If we reuse existing Design System components, it''s 5."}'::jsonb),
  ('large-01-s2', '{"task_text": "Go back to your desk and sketch the first wireframe", "line_text": "The first sketch is ready. This story can go into the sprint."}'::jsonb),
  ('large-02-s1', '{"task_text": "Go to Data & Analytics for the funnel numbers", "line_text": "Here: 42% of users leave at the interest-picker step. That''s the place most worth fixing."}'::jsonb),
  ('large-03-s1', '{"task_text": "Ask the UX Design Engineer about the Chip component", "line_text": "Chip already has 3 states and the code exists. You only need to add a \"selected\" state with an icon."}'::jsonb),
  ('large-04-s1', '{"task_text": "Present your wireframes on the Critique screen", "line_text": "Everyone has seen it. Now go get feedback from each person."}'::jsonb),
  ('large-04-s2', '{"task_text": "Get feedback from the Product Designer", "line_text": "Step 2 has two primary buttons side by side, users will hesitate. Keep just one primary button."}'::jsonb),
  ('large-04-s3', '{"task_text": "Get feedback from the UX Designer", "line_text": "Let people skip the interest-picker step. Don''t force users."}'::jsonb),
  ('large-05-s1', '{"task_text": "Ask the User to try the onboarding flow and observe", "line_text": "Hmm, where do I tap to skip this step? Oh… this faded text? I thought it was disabled."}'::jsonb),
  ('large-05-s2', '{"task_text": "Confirm the problem you just saw with the PM", "line_text": "See that? The user didn''t notice the \"Skip\" button because it''s too faint."}'::jsonb),
  ('large-06-s1', '{"task_text": "Go back to your computer and prepare the spec and prototype", "line_text": "The spec covers the error and loading states. Walk QA through it."}'::jsonb),
  ('large-06-s2', '{"task_text": "Walk QA through the states", "line_text": "Got it. I''ll also test weak network and small screens."}'::jsonb),
  ('large-07-s1', '{"task_text": "Demo the onboarding on the meeting room TV", "line_text": "A smooth demo. Marketing and Customer Success both have comments."}'::jsonb),
  ('large-07-s2', '{"task_text": "Hear feedback from the Growth Manager", "line_text": "I''d like an invite-a-friend step right at the end of onboarding. Can we do that?"}'::jsonb),
  ('large-07-s3', '{"task_text": "Hear feedback from Customer Success", "line_text": "Customers will love it. They ask about this every week."}'::jsonb),
  ('agency-01-s1', '{"task_text": "Go back to your computer and quickly mock up the booking screen", "line_text": "That looks good! A real screen helps the client picture it far better than slides full of text."}'::jsonb),
  ('agency-01-s2', '{"task_text": "Ask the Founder what to emphasise with the client", "line_text": "Don''t show off lots of features. Showing members can book a class in 3 steps is enough."}'::jsonb),
  ('agency-02-s1', '{"task_text": "Ask the Client about the project goals", "line_text": "We have 12 gyms. Members all phone in to book, so reception is overloaded. In 3 months I want 70% of bookings to go through the app."}'::jsonb),
  ('agency-02-s2', '{"task_text": "Go over your notes with the Project Manager", "line_text": "Noted: the goal is fewer booking calls. Every screen from now on has to serve that."}'::jsonb),
  ('agency-03-s1', '{"task_text": "Ask the Business Analyst for the list of screens", "line_text": "The client listed 24 screens. But for members to book a class, 9 screens are enough to get it running."}'::jsonb),
  ('agency-03-s2', '{"task_text": "Go to the Dev team and ask the Tech Lead what fits in time", "line_text": "9 screens fit in 8 weeks. Online payments should wait for phase 2, integrating a payment gateway takes at least 3 weeks."}'::jsonb),
  ('agency-04-s1', '{"task_text": "Go back to your computer and make a concept for the booking flow", "line_text": "Concept done? Before I look, ask the Graphic Designer about the client''s brand identity."}'::jsonb),
  ('agency-04-s2', '{"task_text": "Ask the Graphic Designer about the client''s brand colours", "line_text": "The client''s logo is a deep orange. Use orange only for the primary button, don''t cover the whole screen, it''s too loud."}'::jsonb),
  ('agency-05-s1', '{"task_text": "Present the concept on the meeting room TV", "line_text": "You''ve just finished presenting. The client nods, but seems to want to say something."}'::jsonb),
  ('agency-05-s2', '{"task_text": "Hear the Client''s feedback", "line_text": "I like the booking flow. But the home screen is too empty. Add promo banners, news, and a member leaderboard too."}'::jsonb),
  ('agency-06-s1', '{"task_text": "Don''t say yes yet. Go ask the Project Manager", "line_text": "Those two parts are outside the contract, about 4 more weeks combined. I''ll send an additional quote. We only build it if the client agrees."}'::jsonb),
  ('agency-06-s2', '{"task_text": "Ask the Account Manager to talk to the client", "line_text": "Let me handle it. Just stay friendly: don''t refuse outright, but don''t promise either."}'::jsonb),
  ('agency-07-s1', '{"task_text": "Go to the Pantry and ask the User to try the home screen", "line_text": "When I open the app I want to book right away. These banners hide the button, I thought they were ads so I just scrolled past."}'::jsonb),
  ('agency-07-s2', '{"task_text": "Show the results to the Client", "line_text": "A member really said that? Fine, move the banners down and put the booking button at the top."}'::jsonb),
  ('agency-08-s1', '{"task_text": "Go back to your computer and prepare the spec and prototype", "line_text": "The spec covers all the states. Now walk the Frontend developer through it."}'::jsonb),
  ('agency-08-s2', '{"task_text": "Walk the Frontend Developer through the spec", "line_text": "Got it. I''ll reuse the component set from the last project and just swap in the client''s brand colours."}'::jsonb),
  ('agency-08-s3', '{"task_text": "Invite the Client to sign off the product", "line_text": "The app works exactly like the design. I''m signing off. We''ll do phase 2 with your team too."}'::jsonb)
) as v(id, en) where t.id = v.id;

commit;

-- Kiểm tra: số dòng đã có bản tiếng Anh
select 'tm_characters' as bang, count(*) filter (where i18n ? 'en') as co_tieng_anh, count(*) as tong from tm_characters
union all select 'tm_rooms', count(*) filter (where i18n ? 'en'), count(*) from tm_rooms
union all select 'tm_quests', count(*) filter (where i18n ? 'en'), count(*) from tm_quests
union all select 'tm_quest_steps', count(*) filter (where i18n ? 'en'), count(*) from tm_quest_steps;
